create table carrier_claims_bfd1485 (
	clm_id                                   bigint not null,                          
	bene_id                                  bigint not null,                          
	clm_grp_id                               bigint not null,                          
	last_updated                             timestamp with time zone,                 
	clm_from_dt                              date not null,                            
	clm_thru_dt                              date not null,                            
	clm_clncl_tril_num                       character varying(8),                     
	clm_disp_cd                              character varying(2) not null,            
	clm_pmt_amt                              numeric(10,2) not null,                   
	carr_clm_cntl_num                        character varying(23),                    
	carr_clm_entry_cd                        character(1) not null,                    
	carr_clm_hcpcs_yr_cd                     character(1),                             
	carr_clm_pmt_dnl_cd                      character varying(2) not null,            
	carr_clm_prvdr_asgnmt_ind_sw             character(1),                             
	carr_clm_rfrng_pin_num                   character varying(14) not null, 
	carr_clm_cash_ddctbl_apld_amt            numeric(10,2) not null,
	carr_clm_prmry_pyr_pd_amt                numeric(10,2) not null, 
	carr_num                                 character varying(5) not null,            
	final_action                             character(1) not null,                    
	nch_carr_clm_alowd_amt                   numeric(10,2) not null,                   
	nch_carr_clm_sbmtd_chrg_amt              numeric(10,2) not null,                   
	nch_clm_bene_pmt_amt                     numeric(10,2) not null,                   
	nch_clm_prvdr_pmt_amt                    numeric(10,2) not null,                       
	nch_clm_type_cd                          character varying(2) not null,            
	nch_near_line_rec_ident_cd               character(1) not null,                                
	nch_wkly_proc_dt                         date not null,                            
	prncpal_dgns_cd                          character varying(7),                     
	prncpal_dgns_vrsn_cd                     character(1),                             
	rfr_physn_npi                            character varying(12),                    
	rfr_physn_upin                           character varying(12),                    
	icd_dgns_cd1                             character varying(7),                     
	icd_dgns_cd2                             character varying(7),                     
	icd_dgns_cd3                             character varying(7),                     
	icd_dgns_cd4                             character varying(7),                     
	icd_dgns_cd5                             character varying(7),                     
	icd_dgns_cd6                             character varying(7),                     
	icd_dgns_cd7                             character varying(7),                     
	icd_dgns_cd8                             character varying(7),                     
	icd_dgns_cd9                             character varying(7),                     
	icd_dgns_cd10                            character varying(7),                     
	icd_dgns_cd11                            character varying(7),                     
	icd_dgns_cd12                            character varying(7),                     
	icd_dgns_vrsn_cd1                        character(1),                             
	icd_dgns_vrsn_cd2                        character(1),                             
	icd_dgns_vrsn_cd3                        character(1),                             
	icd_dgns_vrsn_cd4                        character(1),                             
	icd_dgns_vrsn_cd5                        character(1),                             
	icd_dgns_vrsn_cd6                        character(1),                             
	icd_dgns_vrsn_cd7                        character(1),                             
	icd_dgns_vrsn_cd8                        character(1),                             
	icd_dgns_vrsn_cd9                        character(1),                             
	icd_dgns_vrsn_cd10                       character(1),                             
	icd_dgns_vrsn_cd11                       character(1),                             
	icd_dgns_vrsn_cd12                       character(1), 
	constraint carrier_claims_tmp_pkey
	primary key (clm_id)
);                            

${logic.psql-only} SET max_parallel_workers = 6;
${logic.psql-only} SET max_parallel_workers_per_gather = 6;
${logic.psql-only} SET parallel_leader_participation = off;
${logic.psql-only} SET parallel_tuple_cost = 0;
${logic.psql-only} SET parallel_setup_cost = 0;
${logic.psql-only} SET min_parallel_table_scan_size = 0;

insert into carrier_claims_bfd1485(
	clm_id,
	bene_id,
	clm_grp_id,
	last_updated,
	clm_from_dt,
	clm_thru_dt,
	clm_clncl_tril_num,
	clm_disp_cd,
	clm_pmt_amt,
	carr_clm_cntl_num,
	carr_clm_entry_cd,
	carr_clm_hcpcs_yr_cd,
	carr_clm_pmt_dnl_cd,
	carr_clm_prvdr_asgnmt_ind_sw,
	carr_clm_rfrng_pin_num,
	carr_clm_cash_ddctbl_apld_amt,
	carr_clm_prmry_pyr_pd_amt,
	carr_num,
	final_action,
	nch_carr_clm_alowd_amt,
	nch_carr_clm_sbmtd_chrg_amt,
	nch_clm_bene_pmt_amt,
	nch_clm_prvdr_pmt_amt,
	nch_clm_type_cd,
	nch_near_line_rec_ident_cd,
	nch_wkly_proc_dt,
	prncpal_dgns_cd,
	prncpal_dgns_vrsn_cd,
	rfr_physn_npi,
	rfr_physn_upin,
	icd_dgns_cd1,
	icd_dgns_cd2,
	icd_dgns_cd3,
	icd_dgns_cd4,
	icd_dgns_cd5,
	icd_dgns_cd6,
	icd_dgns_cd7,
	icd_dgns_cd8,
	icd_dgns_cd9,
	icd_dgns_cd10,
	icd_dgns_cd11,
	icd_dgns_cd12,
	icd_dgns_vrsn_cd1,
	icd_dgns_vrsn_cd2,
	icd_dgns_vrsn_cd3,
	icd_dgns_vrsn_cd4,
	icd_dgns_vrsn_cd5,
	icd_dgns_vrsn_cd6,
	icd_dgns_vrsn_cd7,
	icd_dgns_vrsn_cd8,
	icd_dgns_vrsn_cd9,
	icd_dgns_vrsn_cd10,
	icd_dgns_vrsn_cd11,
	icd_dgns_vrsn_cd12
)
${logic.psql-only} select
	${logic.psql-only} cast(clm_id as bigint),
	${logic.psql-only} cast(bene_id as bigint),
	${logic.psql-only} cast(clm_grp_id as bigint),
 ${logic.hsql-only} select   
    ${logic.hsql-only} convert(clm_id, SQL_BIGINT),
	${logic.hsql-only} convert(bene_id, SQL_BIGINT),
	${logic.hsql-only} convert(clm_grp_id, SQL_BIGINT),
	last_updated,
	clm_from_dt,
	clm_thru_dt,
	clm_clncl_tril_num,
	clm_disp_cd,
	clm_pmt_amt,
	carr_clm_cntl_num,
	carr_clm_entry_cd,
	carr_clm_hcpcs_yr_cd,
	carr_clm_pmt_dnl_cd,
	carr_clm_prvdr_asgnmt_ind_sw,
	carr_clm_rfrng_pin_num,
	carr_clm_cash_ddctbl_apld_amt,
	carr_clm_prmry_pyr_pd_amt,
	carr_num,
	final_action,
	nch_carr_clm_alowd_amt,
	nch_carr_clm_sbmtd_chrg_amt,
	nch_clm_bene_pmt_amt,
	nch_clm_prvdr_pmt_amt,
	nch_clm_type_cd,
	nch_near_line_rec_ident_cd,
	nch_wkly_proc_dt,
	prncpal_dgns_cd,
	prncpal_dgns_vrsn_cd,
	rfr_physn_npi,
	rfr_physn_upin,
	icd_dgns_cd1,
	icd_dgns_cd2,
	icd_dgns_cd3,
	icd_dgns_cd4,
	icd_dgns_cd5,
	icd_dgns_cd6,
	icd_dgns_cd7,
	icd_dgns_cd8,
	icd_dgns_cd9,
	icd_dgns_cd10,
	icd_dgns_cd11,
	icd_dgns_cd12,
	icd_dgns_vrsn_cd1,
	icd_dgns_vrsn_cd2,
	icd_dgns_vrsn_cd3,
	icd_dgns_vrsn_cd4,
	icd_dgns_vrsn_cd5,
	icd_dgns_vrsn_cd6,
	icd_dgns_vrsn_cd7,
	icd_dgns_vrsn_cd8,
	icd_dgns_vrsn_cd9,
	icd_dgns_vrsn_cd10,
	icd_dgns_vrsn_cd11,
	icd_dgns_vrsn_cd12
from
	carrier_claims;