${logic.hsql-only} CREATE TABLE beneficiaries_bfd1485(
	${logic.hsql-only} bene_id						bigint NOT NULL,
	${logic.hsql-only} bene_birth_dt 				date NOT NULL,
	${logic.hsql-only} bene_esrd_ind				char(1), 
	${logic.hsql-only} bene_entlmt_rsn_curr			char(1), 
	${logic.hsql-only} bene_entlmt_rsn_orig			char(1), 
	${logic.hsql-only} bene_mdcr_status_cd			varchar(2), 
	${logic.hsql-only} bene_gvn_name				varchar(15) NOT NULL,
	${logic.hsql-only} bene_mdl_name				char(1), 
	${logic.hsql-only} bene_srnm_name				varchar(24) NOT NULL,
	${logic.hsql-only} bene_pta_trmntn_cd			char(1), 
	${logic.hsql-only} bene_ptb_trmntn_cd			char(1), 
	${logic.hsql-only} bene_zip_cd					varchar(9) NOT NULL,
	${logic.hsql-only} state_code					varchar(2) NOT NULL,
	${logic.hsql-only} bene_county_cd				varchar(10) NOT NULL,
	${logic.hsql-only} bene_sex_ident_cd			char(1) NOT NULL,
	${logic.hsql-only} bene_race_cd					char(1), 
	${logic.hsql-only} rti_race_cd					char(1), 
	${logic.hsql-only} hicn_unhashed				varchar(11),
	${logic.hsql-only} bene_crnt_hic_num			varchar(64) NOT NULL,
	${logic.hsql-only} mbi_num						varchar(11),
	${logic.hsql-only} mbi_hash						varchar(64), 
	${logic.hsql-only} death_dt 					date,
	${logic.hsql-only} age							smallint,
	${logic.hsql-only} rfrnc_yr						smallint,
	${logic.hsql-only} a_mo_cnt						smallint,
	${logic.hsql-only} b_mo_cnt						smallint,
	${logic.hsql-only} buyin_mo_cnt					smallint,
	${logic.hsql-only} hmo_mo_cnt					smallint,
	${logic.hsql-only} rds_mo_cnt					smallint,
	${logic.hsql-only} enrl_src						varchar(3), 
	${logic.hsql-only} sample_group					varchar(2), 
	${logic.hsql-only} efivepct						char(1), 
	${logic.hsql-only} crnt_bic						varchar(2), 
	${logic.hsql-only} v_dod_sw						char(1), 
	${logic.hsql-only} covstart 					date,
	${logic.hsql-only} dual_mo_cnt					smallint,
	${logic.hsql-only} drvd_line_1_adr				varchar(40), 
	${logic.hsql-only} drvd_line_2_adr				varchar(40), 
	${logic.hsql-only} drvd_line_3_adr				varchar(40), 
	${logic.hsql-only} drvd_line_4_adr				varchar(40), 
	${logic.hsql-only} drvd_line_5_adr				varchar(40), 
	${logic.hsql-only} drvd_line_6_adr				varchar(40), 
	${logic.hsql-only} city_name					varchar(100), 
	${logic.hsql-only} state_cd						varchar(2), 
	${logic.hsql-only} state_cnty_zip_cd			varchar(9), 
	${logic.hsql-only} efctv_bgn_dt 				date,
	${logic.hsql-only} efctv_end_dt 				date,
	${logic.hsql-only} fips_state_cnty_jan_cd		varchar(5), 
	${logic.hsql-only} fips_state_cnty_feb_cd		varchar(5), 
	${logic.hsql-only} fips_state_cnty_mar_cd		varchar(5), 
	${logic.hsql-only} fips_state_cnty_apr_cd		varchar(5), 
	${logic.hsql-only} fips_state_cnty_may_cd		varchar(5), 
	${logic.hsql-only} fips_state_cnty_jun_cd		varchar(5), 
	${logic.hsql-only} fips_state_cnty_jul_cd		varchar(5), 
	${logic.hsql-only} fips_state_cnty_aug_cd		varchar(5), 
	${logic.hsql-only} fips_state_cnty_sept_cd		varchar(5), 
	${logic.hsql-only} fips_state_cnty_oct_cd		varchar(5), 
	${logic.hsql-only} fips_state_cnty_nov_cd		varchar(5), 
	${logic.hsql-only} fips_state_cnty_dec_cd		varchar(5), 
	${logic.hsql-only} mdcr_stus_jan_cd				varchar(2), 
	${logic.hsql-only} mdcr_stus_feb_cd				varchar(2), 
	${logic.hsql-only} mdcr_stus_mar_cd				varchar(2), 
	${logic.hsql-only} mdcr_stus_apr_cd				varchar(2), 
	${logic.hsql-only} mdcr_stus_may_cd				varchar(2), 
	${logic.hsql-only} mdcr_stus_jun_cd				varchar(2), 
	${logic.hsql-only} mdcr_stus_jul_cd				varchar(2), 
	${logic.hsql-only} mdcr_stus_aug_cd				varchar(2), 
	${logic.hsql-only} mdcr_stus_sept_cd			varchar(2), 
	${logic.hsql-only} mdcr_stus_oct_cd				varchar(2), 
	${logic.hsql-only} mdcr_stus_nov_cd				varchar(2), 
	${logic.hsql-only} mdcr_stus_dec_cd				varchar(2), 
	${logic.hsql-only} plan_cvrg_mo_cnt 			smallint,
	${logic.hsql-only} mdcr_entlmt_buyin_1_ind		char(1), 
	${logic.hsql-only} mdcr_entlmt_buyin_2_ind		char(1), 
	${logic.hsql-only} mdcr_entlmt_buyin_3_ind		char(1), 
	${logic.hsql-only} mdcr_entlmt_buyin_4_ind		char(1), 
	${logic.hsql-only} mdcr_entlmt_buyin_5_ind		char(1), 
	${logic.hsql-only} mdcr_entlmt_buyin_6_ind		char(1), 
	${logic.hsql-only} mdcr_entlmt_buyin_7_ind		char(1), 
	${logic.hsql-only} mdcr_entlmt_buyin_8_ind		char(1), 
	${logic.hsql-only} mdcr_entlmt_buyin_9_ind		char(1), 
	${logic.hsql-only} mdcr_entlmt_buyin_10_ind		char(1), 
	${logic.hsql-only} mdcr_entlmt_buyin_11_ind		char(1), 
	${logic.hsql-only} mdcr_entlmt_buyin_12_ind		char(1), 
	${logic.hsql-only} hmo_1_ind					char(1), 
	${logic.hsql-only} hmo_2_ind					char(1), 
	${logic.hsql-only} hmo_3_ind					char(1), 
	${logic.hsql-only} hmo_4_ind					char(1), 
	${logic.hsql-only} hmo_5_ind					char(1), 
	${logic.hsql-only} hmo_6_ind					char(1), 
	${logic.hsql-only} hmo_7_ind					char(1), 
	${logic.hsql-only} hmo_8_ind					char(1), 
	${logic.hsql-only} hmo_9_ind					char(1), 
	${logic.hsql-only} hmo_10_ind					char(1), 
	${logic.hsql-only} hmo_11_ind					char(1), 
	${logic.hsql-only} hmo_12_ind					char(1), 
	${logic.hsql-only} ptc_cntrct_jan_id			varchar(5), 
	${logic.hsql-only} ptc_cntrct_feb_id			varchar(5), 
	${logic.hsql-only} ptc_cntrct_mar_id			varchar(5), 
	${logic.hsql-only} ptc_cntrct_apr_id			varchar(5), 
	${logic.hsql-only} ptc_cntrct_may_id			varchar(5), 
	${logic.hsql-only} ptc_cntrct_jun_id			varchar(5), 
	${logic.hsql-only} ptc_cntrct_jul_id			varchar(5), 
	${logic.hsql-only} ptc_cntrct_aug_id			varchar(5), 
	${logic.hsql-only} ptc_cntrct_sept_id			varchar(5), 
	${logic.hsql-only} ptc_cntrct_oct_id			varchar(5), 
	${logic.hsql-only} ptc_cntrct_nov_id			varchar(5), 
	${logic.hsql-only} ptc_cntrct_dec_id			varchar(5), 
	${logic.hsql-only} ptc_pbp_jan_id				varchar(3), 
	${logic.hsql-only} ptc_pbp_feb_id				varchar(3), 
	${logic.hsql-only} ptc_pbp_mar_id				varchar(3), 
	${logic.hsql-only} ptc_pbp_apr_id				varchar(3), 
	${logic.hsql-only} ptc_pbp_may_id				varchar(3), 
	${logic.hsql-only} ptc_pbp_jun_id				varchar(3), 
	${logic.hsql-only} ptc_pbp_jul_id				varchar(3), 
	${logic.hsql-only} ptc_pbp_aug_id				varchar(3), 
	${logic.hsql-only} ptc_pbp_sept_id				varchar(3), 
	${logic.hsql-only} ptc_pbp_oct_id				varchar(3), 
	${logic.hsql-only} ptc_pbp_nov_id				varchar(3), 
	${logic.hsql-only} ptc_pbp_dec_id				varchar(3), 
	${logic.hsql-only} ptc_plan_type_jan_cd			varchar(3), 
	${logic.hsql-only} ptc_plan_type_feb_cd			varchar(3), 
	${logic.hsql-only} ptc_plan_type_mar_cd			varchar(3), 
	${logic.hsql-only} ptc_plan_type_apr_cd			varchar(3), 
	${logic.hsql-only} ptc_plan_type_may_cd			varchar(3), 
	${logic.hsql-only} ptc_plan_type_jun_cd			varchar(3), 
	${logic.hsql-only} ptc_plan_type_jul_cd			varchar(3), 
	${logic.hsql-only} ptc_plan_type_aug_cd			varchar(3), 
	${logic.hsql-only} ptc_plan_type_sept_cd		varchar(3), 
	${logic.hsql-only} ptc_plan_type_oct_cd			varchar(3), 
	${logic.hsql-only} ptc_plan_type_nov_cd			varchar(3), 
	${logic.hsql-only} ptc_plan_type_dec_cd			varchar(3), 
	${logic.hsql-only} ptd_cntrct_jan_id			varchar(5), 
	${logic.hsql-only} ptd_cntrct_feb_id			varchar(5), 
	${logic.hsql-only} ptd_cntrct_mar_id			varchar(5), 
	${logic.hsql-only} ptd_cntrct_apr_id			varchar(5), 
	${logic.hsql-only} ptd_cntrct_may_id			varchar(5), 
	${logic.hsql-only} ptd_cntrct_jun_id			varchar(5), 
	${logic.hsql-only} ptd_cntrct_jul_id			varchar(5), 
	${logic.hsql-only} ptd_cntrct_aug_id			varchar(5), 
	${logic.hsql-only} ptd_cntrct_sept_id			varchar(5), 
	${logic.hsql-only} ptd_cntrct_oct_id			varchar(5), 
	${logic.hsql-only} ptd_cntrct_nov_id			varchar(5), 
	${logic.hsql-only} ptd_cntrct_dec_id			varchar(5), 
	${logic.hsql-only} ptd_pbp_jan_id				varchar(3), 
	${logic.hsql-only} ptd_pbp_feb_id				varchar(3), 
	${logic.hsql-only} ptd_pbp_mar_id				varchar(3), 
	${logic.hsql-only} ptd_pbp_apr_id				varchar(3), 
	${logic.hsql-only} ptd_pbp_may_id				varchar(3), 
	${logic.hsql-only} ptd_pbp_jun_id				varchar(3), 
	${logic.hsql-only} ptd_pbp_jul_id				varchar(3), 
	${logic.hsql-only} ptd_pbp_aug_id				varchar(3), 
	${logic.hsql-only} ptd_pbp_sept_id				varchar(3), 
	${logic.hsql-only} ptd_pbp_oct_id				varchar(3), 
	${logic.hsql-only} ptd_pbp_nov_id				varchar(3), 
	${logic.hsql-only} ptd_pbp_dec_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_jan_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_feb_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_mar_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_apr_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_may_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_jun_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_jul_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_aug_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_sept_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_oct_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_nov_id				varchar(3), 
	${logic.hsql-only} ptd_sgmt_dec_id				varchar(3), 
	${logic.hsql-only} rds_jan_ind					char(1), 
	${logic.hsql-only} rds_feb_ind					char(1), 
	${logic.hsql-only} rds_mar_ind					char(1), 
	${logic.hsql-only} rds_apr_ind					char(1), 
	${logic.hsql-only} rds_may_ind					char(1), 
	${logic.hsql-only} rds_jun_ind					char(1), 
	${logic.hsql-only} rds_jul_ind					char(1), 
	${logic.hsql-only} rds_aug_ind					char(1), 
	${logic.hsql-only} rds_sept_ind					char(1), 
	${logic.hsql-only} rds_oct_ind					char(1), 
	${logic.hsql-only} rds_nov_ind					char(1), 
	${logic.hsql-only} rds_dec_ind					char(1), 
	${logic.hsql-only} meta_dual_elgbl_stus_jan_cd	varchar(2), 
	${logic.hsql-only} meta_dual_elgbl_stus_feb_cd	varchar(2), 
	${logic.hsql-only} meta_dual_elgbl_stus_mar_cd	varchar(2), 
	${logic.hsql-only} meta_dual_elgbl_stus_apr_cd	varchar(2), 
	${logic.hsql-only} meta_dual_elgbl_stus_may_cd	varchar(2), 
	${logic.hsql-only} meta_dual_elgbl_stus_jun_cd	varchar(2), 
	${logic.hsql-only} meta_dual_elgbl_stus_jul_cd	varchar(2), 
	${logic.hsql-only} meta_dual_elgbl_stus_aug_cd	varchar(2), 
	${logic.hsql-only} meta_dual_elgbl_stus_sept_cd	varchar(2), 
	${logic.hsql-only} meta_dual_elgbl_stus_oct_cd	varchar(2), 
	${logic.hsql-only} meta_dual_elgbl_stus_nov_cd	varchar(2), 
	${logic.hsql-only} meta_dual_elgbl_stus_dec_cd	varchar(2), 
	${logic.hsql-only} cst_shr_grp_jan_cd			varchar(2), 
	${logic.hsql-only} cst_shr_grp_feb_cd			varchar(2), 
	${logic.hsql-only} cst_shr_grp_mar_cd			varchar(2), 
	${logic.hsql-only} cst_shr_grp_apr_cd			varchar(2), 
	${logic.hsql-only} cst_shr_grp_may_cd			varchar(2), 
	${logic.hsql-only} cst_shr_grp_jun_cd			varchar(2), 
	${logic.hsql-only} cst_shr_grp_jul_cd			varchar(2), 
	${logic.hsql-only} cst_shr_grp_aug_cd			varchar(2), 
	${logic.hsql-only} cst_shr_grp_sept_cd			varchar(2), 
	${logic.hsql-only} cst_shr_grp_oct_cd			varchar(2), 
	${logic.hsql-only} cst_shr_grp_nov_cd			varchar(2), 
	${logic.hsql-only} cst_shr_grp_dec_cd			varchar(2), 
	${logic.hsql-only} last_updated					timestamp with time zone,
	${logic.hsql-only} bene_link_key 				numeric(38,0),
	${logic.hsql-only} constraint beneficiaries_bfd1485_pkey
	${logic.hsql-only} primary key (bene_id) );

${logic.psql-only} SET max_parallel_workers = 24;
${logic.psql-only} SET max_parallel_workers_per_gather = 20;
${logic.psql-only} SET parallel_leader_participation = off;
${logic.psql-only} SET parallel_tuple_cost = 0;
${logic.psql-only} SET parallel_setup_cost = 0;
${logic.psql-only} SET min_parallel_table_scan_size = 0;

${logic.hsql-only} insert into beneficiaries_bfd1485 (
	${logic.hsql-only} bene_id,
	${logic.hsql-only} bene_birth_dt,
	${logic.hsql-only} bene_esrd_ind,
	${logic.hsql-only} bene_entlmt_rsn_curr,
	${logic.hsql-only} bene_entlmt_rsn_orig,
	${logic.hsql-only} bene_mdcr_status_cd,
	${logic.hsql-only} bene_gvn_name,
	${logic.hsql-only} bene_mdl_name,
	${logic.hsql-only} bene_srnm_name,
	${logic.hsql-only} bene_pta_trmntn_cd,
	${logic.hsql-only} bene_ptb_trmntn_cd,
	${logic.hsql-only} bene_zip_cd,
	${logic.hsql-only} state_code,
	${logic.hsql-only} bene_county_cd,
	${logic.hsql-only} bene_sex_ident_cd,
	${logic.hsql-only} bene_race_cd,
	${logic.hsql-only} rti_race_cd,
	${logic.hsql-only} hicn_unhashed,
	${logic.hsql-only} bene_crnt_hic_num,
	${logic.hsql-only} mbi_num,
	${logic.hsql-only} mbi_hash,
	${logic.hsql-only} death_dt,
	${logic.hsql-only} age,
	${logic.hsql-only} rfrnc_yr,
	${logic.hsql-only} a_mo_cnt,
	${logic.hsql-only} b_mo_cnt,
	${logic.hsql-only} buyin_mo_cnt,
	${logic.hsql-only} hmo_mo_cnt,
	${logic.hsql-only} rds_mo_cnt,
	${logic.hsql-only} enrl_src,
	${logic.hsql-only} sample_group,
	${logic.hsql-only} efivepct,
	${logic.hsql-only} crnt_bic,
	${logic.hsql-only} v_dod_sw,
	${logic.hsql-only} covstart,
	${logic.hsql-only} dual_mo_cnt,
	${logic.hsql-only} drvd_line_1_adr,
	${logic.hsql-only} drvd_line_2_adr,
	${logic.hsql-only} drvd_line_3_adr,
	${logic.hsql-only} drvd_line_4_adr,
	${logic.hsql-only} drvd_line_5_adr,
	${logic.hsql-only} drvd_line_6_adr,
	${logic.hsql-only} city_name,
	${logic.hsql-only} state_cd,
	${logic.hsql-only} state_cnty_zip_cd,
	${logic.hsql-only} efctv_bgn_dt,
	${logic.hsql-only} efctv_end_dt,
	${logic.hsql-only} fips_state_cnty_jan_cd,
	${logic.hsql-only} fips_state_cnty_feb_cd,
	${logic.hsql-only} fips_state_cnty_mar_cd,
	${logic.hsql-only} fips_state_cnty_apr_cd,
	${logic.hsql-only} fips_state_cnty_may_cd,
	${logic.hsql-only} fips_state_cnty_jun_cd,
	${logic.hsql-only} fips_state_cnty_jul_cd,
	${logic.hsql-only} fips_state_cnty_aug_cd,
	${logic.hsql-only} fips_state_cnty_sept_cd,
	${logic.hsql-only} fips_state_cnty_oct_cd,
	${logic.hsql-only} fips_state_cnty_nov_cd,
	${logic.hsql-only} fips_state_cnty_dec_cd,
	${logic.hsql-only} mdcr_stus_jan_cd,
	${logic.hsql-only} mdcr_stus_feb_cd,
	${logic.hsql-only} mdcr_stus_mar_cd,
	${logic.hsql-only} mdcr_stus_apr_cd,
	${logic.hsql-only} mdcr_stus_may_cd,
	${logic.hsql-only} mdcr_stus_jun_cd,
	${logic.hsql-only} mdcr_stus_jul_cd,
	${logic.hsql-only} mdcr_stus_aug_cd,
	${logic.hsql-only} mdcr_stus_sept_cd,
	${logic.hsql-only} mdcr_stus_oct_cd,
	${logic.hsql-only} mdcr_stus_nov_cd,
	${logic.hsql-only} mdcr_stus_dec_cd,
	${logic.hsql-only} plan_cvrg_mo_cnt,
	${logic.hsql-only} mdcr_entlmt_buyin_1_ind,
	${logic.hsql-only} mdcr_entlmt_buyin_2_ind,
	${logic.hsql-only} mdcr_entlmt_buyin_3_ind,
	${logic.hsql-only} mdcr_entlmt_buyin_4_ind,
	${logic.hsql-only} mdcr_entlmt_buyin_5_ind,
	${logic.hsql-only} mdcr_entlmt_buyin_6_ind,
	${logic.hsql-only} mdcr_entlmt_buyin_7_ind,
	${logic.hsql-only} mdcr_entlmt_buyin_8_ind,
	${logic.hsql-only} mdcr_entlmt_buyin_9_ind,
	${logic.hsql-only} mdcr_entlmt_buyin_10_ind,
	${logic.hsql-only} mdcr_entlmt_buyin_11_ind,
	${logic.hsql-only} mdcr_entlmt_buyin_12_ind,
	${logic.hsql-only} hmo_1_ind,
	${logic.hsql-only} hmo_2_ind,
	${logic.hsql-only} hmo_3_ind,
	${logic.hsql-only} hmo_4_ind,
	${logic.hsql-only} hmo_5_ind,
	${logic.hsql-only} hmo_6_ind,
	${logic.hsql-only} hmo_7_ind,
	${logic.hsql-only} hmo_8_ind,
	${logic.hsql-only} hmo_9_ind,
	${logic.hsql-only} hmo_10_ind,
	${logic.hsql-only} hmo_11_ind,
	${logic.hsql-only} hmo_12_ind,
	${logic.hsql-only} ptc_cntrct_jan_id,
	${logic.hsql-only} ptc_cntrct_feb_id,
	${logic.hsql-only} ptc_cntrct_mar_id,
	${logic.hsql-only} ptc_cntrct_apr_id,
	${logic.hsql-only} ptc_cntrct_may_id,
	${logic.hsql-only} ptc_cntrct_jun_id,
	${logic.hsql-only} ptc_cntrct_jul_id,
	${logic.hsql-only} ptc_cntrct_aug_id,
	${logic.hsql-only} ptc_cntrct_sept_id,
	${logic.hsql-only} ptc_cntrct_oct_id,
	${logic.hsql-only} ptc_cntrct_nov_id,
	${logic.hsql-only} ptc_cntrct_dec_id,
	${logic.hsql-only} ptc_pbp_jan_id,
	${logic.hsql-only} ptc_pbp_feb_id,
	${logic.hsql-only} ptc_pbp_mar_id,
	${logic.hsql-only} ptc_pbp_apr_id,
	${logic.hsql-only} ptc_pbp_may_id,
	${logic.hsql-only} ptc_pbp_jun_id,
	${logic.hsql-only} ptc_pbp_jul_id,
	${logic.hsql-only} ptc_pbp_aug_id,
	${logic.hsql-only} ptc_pbp_sept_id,
	${logic.hsql-only} ptc_pbp_oct_id,
	${logic.hsql-only} ptc_pbp_nov_id,
	${logic.hsql-only} ptc_pbp_dec_id,
	${logic.hsql-only} ptc_plan_type_jan_cd,
	${logic.hsql-only} ptc_plan_type_feb_cd,
	${logic.hsql-only} ptc_plan_type_mar_cd,
	${logic.hsql-only} ptc_plan_type_apr_cd,
	${logic.hsql-only} ptc_plan_type_may_cd,
	${logic.hsql-only} ptc_plan_type_jun_cd,
	${logic.hsql-only} ptc_plan_type_jul_cd,
	${logic.hsql-only} ptc_plan_type_aug_cd,
	${logic.hsql-only} ptc_plan_type_sept_cd,
	${logic.hsql-only} ptc_plan_type_oct_cd,
	${logic.hsql-only} ptc_plan_type_nov_cd,
	${logic.hsql-only} ptc_plan_type_dec_cd,
	${logic.hsql-only} ptd_cntrct_jan_id,
	${logic.hsql-only} ptd_cntrct_feb_id,
	${logic.hsql-only} ptd_cntrct_mar_id,
	${logic.hsql-only} ptd_cntrct_apr_id,
	${logic.hsql-only} ptd_cntrct_may_id,
	${logic.hsql-only} ptd_cntrct_jun_id,
	${logic.hsql-only} ptd_cntrct_jul_id,
	${logic.hsql-only} ptd_cntrct_aug_id,
	${logic.hsql-only} ptd_cntrct_sept_id,
	${logic.hsql-only} ptd_cntrct_oct_id,
	${logic.hsql-only} ptd_cntrct_nov_id,
	${logic.hsql-only} ptd_cntrct_dec_id,
	${logic.hsql-only} ptd_pbp_jan_id,
	${logic.hsql-only} ptd_pbp_feb_id,
	${logic.hsql-only} ptd_pbp_mar_id,
	${logic.hsql-only} ptd_pbp_apr_id,
	${logic.hsql-only} ptd_pbp_may_id,
	${logic.hsql-only} ptd_pbp_jun_id,
	${logic.hsql-only} ptd_pbp_jul_id,
	${logic.hsql-only} ptd_pbp_aug_id,
	${logic.hsql-only} ptd_pbp_sept_id,
	${logic.hsql-only} ptd_pbp_oct_id,
	${logic.hsql-only} ptd_pbp_nov_id,
	${logic.hsql-only} ptd_pbp_dec_id,
	${logic.hsql-only} ptd_sgmt_jan_id,
	${logic.hsql-only} ptd_sgmt_feb_id,
	${logic.hsql-only} ptd_sgmt_mar_id,
	${logic.hsql-only} ptd_sgmt_apr_id,
	${logic.hsql-only} ptd_sgmt_may_id,
	${logic.hsql-only} ptd_sgmt_jun_id,
	${logic.hsql-only} ptd_sgmt_jul_id,
	${logic.hsql-only} ptd_sgmt_aug_id,
	${logic.hsql-only} ptd_sgmt_sept_id,
	${logic.hsql-only} ptd_sgmt_oct_id,
	${logic.hsql-only} ptd_sgmt_nov_id,
	${logic.hsql-only} ptd_sgmt_dec_id,
	${logic.hsql-only} rds_jan_ind,
	${logic.hsql-only} rds_feb_ind,
	${logic.hsql-only} rds_mar_ind,
	${logic.hsql-only} rds_apr_ind,
	${logic.hsql-only} rds_may_ind,
	${logic.hsql-only} rds_jun_ind,
	${logic.hsql-only} rds_jul_ind,
	${logic.hsql-only} rds_aug_ind,
	${logic.hsql-only} rds_sept_ind,
	${logic.hsql-only} rds_oct_ind,
	${logic.hsql-only} rds_nov_ind,
	${logic.hsql-only} rds_dec_ind,
	${logic.hsql-only} meta_dual_elgbl_stus_jan_cd,
	${logic.hsql-only} meta_dual_elgbl_stus_feb_cd,
	${logic.hsql-only} meta_dual_elgbl_stus_mar_cd,
	${logic.hsql-only} meta_dual_elgbl_stus_apr_cd,
	${logic.hsql-only} meta_dual_elgbl_stus_may_cd,
	${logic.hsql-only} meta_dual_elgbl_stus_jun_cd,
	${logic.hsql-only} meta_dual_elgbl_stus_jul_cd,
	${logic.hsql-only} meta_dual_elgbl_stus_aug_cd,
	${logic.hsql-only} meta_dual_elgbl_stus_sept_cd,
	${logic.hsql-only} meta_dual_elgbl_stus_oct_cd,
	${logic.hsql-only} meta_dual_elgbl_stus_nov_cd,
	${logic.hsql-only} meta_dual_elgbl_stus_dec_cd,
	${logic.hsql-only} cst_shr_grp_jan_cd,
	${logic.hsql-only} cst_shr_grp_feb_cd,
	${logic.hsql-only} cst_shr_grp_mar_cd,
	${logic.hsql-only} cst_shr_grp_apr_cd,
	${logic.hsql-only} cst_shr_grp_may_cd,
	${logic.hsql-only} cst_shr_grp_jun_cd,
	${logic.hsql-only} cst_shr_grp_jul_cd,
	${logic.hsql-only} cst_shr_grp_aug_cd,
	${logic.hsql-only} cst_shr_grp_sept_cd,
	${logic.hsql-only} cst_shr_grp_oct_cd,
	${logic.hsql-only} cst_shr_grp_nov_cd,
	${logic.hsql-only} cst_shr_grp_dec_cd,
	${logic.hsql-only} last_updated,
	${logic.hsql-only} bene_link_key )
${logic.psql-only} create table beneficiaries_bfd1485 as
select
	${logic.psql-only} cast(bene_id as bigint),  
	${logic.hsql-only} convert(bene_id, SQL_BIGINT),
	bene_birth_dt,
	bene_esrd_ind, 
	bene_entlmt_rsn_curr,
	bene_entlmt_rsn_orig,
	bene_mdcr_status_cd,
	bene_gvn_name,
	bene_mdl_name,
	bene_srnm_name,
	bene_pta_trmntn_cd,
	bene_ptb_trmntn_cd,
	bene_zip_cd,
	state_code,
	bene_county_cd,
	bene_sex_ident_cd,
	bene_race_cd,
	rti_race_cd	,
	hicn_unhashed,
	bene_crnt_hic_num,
	mbi_num,
	mbi_hash,
	death_dt,
	${logic.psql-only} cast(age as smallint),
	${logic.hsql-only} convert(age, SQL_SMALLINT),
	${logic.psql-only} cast(rfrnc_yr as smallint),
	${logic.hsql-only} convert(rfrnc_yr, SQL_SMALLINT),
	${logic.psql-only} cast(a_mo_cnt as smallint),
	${logic.hsql-only} convert(a_mo_cnt, SQL_SMALLINT),
	${logic.psql-only} cast(b_mo_cnt as smallint),
	${logic.hsql-only} convert(b_mo_cnt, SQL_SMALLINT),
	${logic.psql-only} cast(buyin_mo_cnt as smallint),
	${logic.hsql-only} convert(buyin_mo_cnt, SQL_SMALLINT),
	${logic.psql-only} cast(hmo_mo_cnt as smallint),
	${logic.hsql-only} convert(hmo_mo_cnt, SQL_SMALLINT),
	${logic.psql-only} cast(rds_mo_cnt as smallint),
	${logic.hsql-only} convert(rds_mo_cnt, SQL_SMALLINT),
	enrl_src,
	sample_group,
	efivepct,
	crnt_bic,
	v_dod_sw,
	covstart,
	${logic.psql-only} cast(dual_mo_cnt as smallint),
	${logic.hsql-only} convert(dual_mo_cnt, SQL_SMALLINT),
	drvd_line_1_adr,
	drvd_line_2_adr,
	drvd_line_3_adr,
	drvd_line_4_adr,
	drvd_line_5_adr,
	drvd_line_6_adr,
	city_name,
	state_cd,
	state_cnty_zip_cd,
	efctv_bgn_dt,
	efctv_end_dt,
	fips_state_cnty_jan_cd,
	fips_state_cnty_feb_cd,
	fips_state_cnty_mar_cd,
	fips_state_cnty_apr_cd,
	fips_state_cnty_may_cd,
	fips_state_cnty_jun_cd,
	fips_state_cnty_jul_cd,
	fips_state_cnty_aug_cd,
	fips_state_cnty_sept_cd,
	fips_state_cnty_oct_cd,
	fips_state_cnty_nov_cd,
	fips_state_cnty_dec_cd,
	mdcr_stus_jan_cd,
	mdcr_stus_feb_cd,
	mdcr_stus_mar_cd,
	mdcr_stus_apr_cd,
	mdcr_stus_may_cd,
	mdcr_stus_jun_cd,
	mdcr_stus_jul_cd,
	mdcr_stus_aug_cd,
	mdcr_stus_sept_cd,
	mdcr_stus_oct_cd,
	mdcr_stus_nov_cd,
	mdcr_stus_dec_cd,
	plan_cvrg_mo_cnt,
	mdcr_entlmt_buyin_1_ind,
	mdcr_entlmt_buyin_2_ind,
	mdcr_entlmt_buyin_3_ind,
	mdcr_entlmt_buyin_4_ind,
	mdcr_entlmt_buyin_5_ind,
	mdcr_entlmt_buyin_6_ind,
	mdcr_entlmt_buyin_7_ind,
	mdcr_entlmt_buyin_8_ind,
	mdcr_entlmt_buyin_9_ind,
	mdcr_entlmt_buyin_10_ind,
	mdcr_entlmt_buyin_11_ind,
	mdcr_entlmt_buyin_12_ind,
	hmo_1_ind,
	hmo_2_ind,
	hmo_3_ind,
	hmo_4_ind,
	hmo_5_ind,
	hmo_6_ind,
	hmo_7_ind,
	hmo_8_ind,
	hmo_9_ind,
	hmo_10_ind,
	hmo_11_ind,
	hmo_12_ind,
	ptc_cntrct_jan_id,
	ptc_cntrct_feb_id,
	ptc_cntrct_mar_id,
	ptc_cntrct_apr_id,
	ptc_cntrct_may_id,
	ptc_cntrct_jun_id,
	ptc_cntrct_jul_id,
	ptc_cntrct_aug_id,
	ptc_cntrct_sept_id,
	ptc_cntrct_oct_id,
	ptc_cntrct_nov_id,
	ptc_cntrct_dec_id,
	ptc_pbp_jan_id,
	ptc_pbp_feb_id,
	ptc_pbp_mar_id,
	ptc_pbp_apr_id,
	ptc_pbp_may_id,
	ptc_pbp_jun_id,
	ptc_pbp_jul_id,
	ptc_pbp_aug_id,
	ptc_pbp_sept_id,
	ptc_pbp_oct_id,
	ptc_pbp_nov_id,
	ptc_pbp_dec_id,
	ptc_plan_type_jan_cd,
	ptc_plan_type_feb_cd,
	ptc_plan_type_mar_cd,
	ptc_plan_type_apr_cd,
	ptc_plan_type_may_cd,
	ptc_plan_type_jun_cd,
	ptc_plan_type_jul_cd,
	ptc_plan_type_aug_cd,
	ptc_plan_type_sept_cd,
	ptc_plan_type_oct_cd,
	ptc_plan_type_nov_cd,
	ptc_plan_type_dec_cd,
	ptd_cntrct_jan_id,
	ptd_cntrct_feb_id,
	ptd_cntrct_mar_id,
	ptd_cntrct_apr_id,
	ptd_cntrct_may_id,
	ptd_cntrct_jun_id,
	ptd_cntrct_jul_id,
	ptd_cntrct_aug_id,
	ptd_cntrct_sept_id,
	ptd_cntrct_oct_id,
	ptd_cntrct_nov_id,
	ptd_cntrct_dec_id,
	ptd_pbp_jan_id,
	ptd_pbp_feb_id,
	ptd_pbp_mar_id,
	ptd_pbp_apr_id,
	ptd_pbp_may_id,
	ptd_pbp_jun_id,
	ptd_pbp_jul_id,
	ptd_pbp_aug_id,
	ptd_pbp_sept_id,
	ptd_pbp_oct_id,
	ptd_pbp_nov_id,
	ptd_pbp_dec_id,
	ptd_sgmt_jan_id,
	ptd_sgmt_feb_id,
	ptd_sgmt_mar_id,
	ptd_sgmt_apr_id,
	ptd_sgmt_may_id,
	ptd_sgmt_jun_id,
	ptd_sgmt_jul_id,
	ptd_sgmt_aug_id,
	ptd_sgmt_sept_id,
	ptd_sgmt_oct_id,
	ptd_sgmt_nov_id,
	ptd_sgmt_dec_id,
	rds_jan_ind,
	rds_feb_ind,
	rds_mar_ind,
	rds_apr_ind,
	rds_may_ind,
	rds_jun_ind,
	rds_jul_ind,
	rds_aug_ind,
	rds_sept_ind,
	rds_oct_ind,
	rds_nov_ind,
	rds_dec_ind,
	meta_dual_elgbl_stus_jan_cd,
	meta_dual_elgbl_stus_feb_cd,
	meta_dual_elgbl_stus_mar_cd,
	meta_dual_elgbl_stus_apr_cd,
	meta_dual_elgbl_stus_may_cd,
	meta_dual_elgbl_stus_jun_cd,
	meta_dual_elgbl_stus_jul_cd,
	meta_dual_elgbl_stus_aug_cd,
	meta_dual_elgbl_stus_sept_cd,
	meta_dual_elgbl_stus_oct_cd,
	meta_dual_elgbl_stus_nov_cd,
	meta_dual_elgbl_stus_dec_cd,
	cst_shr_grp_jan_cd,
	cst_shr_grp_feb_cd,
	cst_shr_grp_mar_cd,
	cst_shr_grp_apr_cd,
	cst_shr_grp_may_cd,
	cst_shr_grp_jun_cd,
	cst_shr_grp_jul_cd,
	cst_shr_grp_aug_cd,
	cst_shr_grp_sept_cd,
	cst_shr_grp_oct_cd,
	cst_shr_grp_nov_cd,
	cst_shr_grp_dec_cd,
	last_updated,
	bene_link_key
from
	beneficiaries;

${logic.psql-only} alter table beneficiaries_bfd1485
${logic.psql-only}     alter column bene_id SET NOT NULL,
${logic.psql-only}     alter column bene_birth_dt SET NOT NULL,
${logic.psql-only}     alter column bene_gvn_name SET NOT NULL,
${logic.psql-only}     alter column bene_srnm_name  SET NOT NULL,
${logic.psql-only}     alter column bene_zip_cd SET NOT NULL,
${logic.psql-only}     alter column state_code SET NOT NULL,
${logic.psql-only}     alter column bene_county_cd SET NOT NULL,
${logic.psql-only}     alter column bene_sex_ident_cd SET NOT NULL,
${logic.psql-only}     alter column bene_crnt_hic_num SET NOT NULL;

${logic.psql-only} alter table beneficiaries_bfd1485
${logic.psql-only}     add CONSTRAINT beneficiaries_bfd1485_pkey PRIMARY KEY (bene_id);