${logic.hsql-only} CREATE TABLE IF NOT EXISTS public.bfd1485_outpatient_claims (
${logic.hsql-only} clm_id 							bigint NOT NULL,
${logic.hsql-only} bene_id 							bigint NOT NULL,
${logic.hsql-only} clm_grp_id				 		bigint NOT NULL,
${logic.hsql-only} last_updated 					timestamp with time zone,
${logic.hsql-only} clm_from_dt 						date NOT NULL,
${logic.hsql-only} clm_thru_dt 						date NOT NULL,
${logic.hsql-only} clm_fac_type_cd					char(1) NOT NULL,
${logic.hsql-only} clm_freq_cd						char(1) NOT NULL,
${logic.hsql-only} clm_mdcr_non_pmt_rsn_cd			varchar(2),
${logic.hsql-only} clm_srvc_clsfctn_type_cd			char(1) NOT NULL,
${logic.hsql-only} clm_mco_pd_sw					char(1),
${logic.hsql-only} clm_pmt_amt						numeric(10,2) NOT NULL,
${logic.hsql-only} clm_op_prvdr_pmt_amt				numeric(10,2) NOT NULL,
${logic.hsql-only} clm_tot_chrg_amt					numeric(10,2) NOT NULL,
${logic.hsql-only} clm_op_bene_pmt_amt				numeric(10,2) NOT NULL,
${logic.hsql-only} claim_query_code					char(1) NOT NULL,
${logic.hsql-only} at_physn_npi						varchar(10),
${logic.hsql-only} at_physn_upin					varchar(9),
${logic.hsql-only} nch_prmry_pyr_cd					char(1),
${logic.hsql-only} nch_clm_type_cd					varchar(2) NOT NULL,
${logic.hsql-only} nch_near_line_rec_ident_cd		char(1) NOT NULL,
${logic.hsql-only} nch_wkly_proc_dt 				date NOT NULL,
${logic.hsql-only} nch_bene_blood_ddctbl_lblty_am	numeric(10,2) NOT NULL,
${logic.hsql-only} nch_bene_ptb_coinsrnc_amt		numeric(10,2) NOT NULL,
${logic.hsql-only} nch_bene_ptb_ddctbl_amt			numeric(10,2) NOT NULL,
${logic.hsql-only} nch_prmry_pyr_clm_pd_amt			numeric(10,2) NOT NULL,
${logic.hsql-only} nch_profnl_cmpnt_chrg_amt		numeric(10,2) NOT NULL,
${logic.hsql-only} fi_clm_proc_dt					date,
${logic.hsql-only} fi_num							varchar(5),
${logic.hsql-only} fi_doc_clm_cntl_num				varchar(23),
${logic.hsql-only} fi_orig_clm_cntl_num				varchar(23),
${logic.hsql-only} fst_dgns_e_cd					varchar(7),
${logic.hsql-only} fst_dgns_e_vrsn_cd				char(1),
${logic.hsql-only} prncpal_dgns_cd					varchar(7),
${logic.hsql-only} prncpal_dgns_vrsn_cd				char(1),
${logic.hsql-only} prvdr_num						varchar(9) NOT NULL,
${logic.hsql-only} prvdr_state_cd					varchar(2) NOT NULL,
${logic.hsql-only} org_npi_num						varchar(10),
${logic.hsql-only} op_physn_npi						varchar(10),
${logic.hsql-only} op_physn_upin					varchar(9),
${logic.hsql-only} ot_physn_npi						varchar(10),
${logic.hsql-only} ot_physn_upin					varchar(9),
${logic.hsql-only} ptnt_dschrg_stus_cd				varchar(2),
${logic.hsql-only} final_action						char(1) NOT NULL,
${logic.hsql-only} rsn_visit_cd1					varchar(7),
${logic.hsql-only} rsn_visit_vrsn_cd1				char(1),
${logic.hsql-only} rsn_visit_cd2					varchar(7),
${logic.hsql-only} rsn_visit_vrsn_cd2				char(1),
${logic.hsql-only} rsn_visit_cd3					varchar(7),
${logic.hsql-only} rsn_visit_vrsn_cd3				char(1),
${logic.hsql-only} icd_dgns_cd1						varchar(7),
${logic.hsql-only} icd_dgns_cd2						varchar(7),
${logic.hsql-only} icd_dgns_cd3						varchar(7),
${logic.hsql-only} icd_dgns_cd4						varchar(7),
${logic.hsql-only} icd_dgns_cd5						varchar(7),
${logic.hsql-only} icd_dgns_cd6						varchar(7),
${logic.hsql-only} icd_dgns_cd7						varchar(7),
${logic.hsql-only} icd_dgns_cd8						varchar(7),
${logic.hsql-only} icd_dgns_cd9						varchar(7),
${logic.hsql-only} icd_dgns_cd10					varchar(7),
${logic.hsql-only} icd_dgns_cd11					varchar(7),
${logic.hsql-only} icd_dgns_cd12					varchar(7),
${logic.hsql-only} icd_dgns_cd13					varchar(7),
${logic.hsql-only} icd_dgns_cd14					varchar(7),
${logic.hsql-only} icd_dgns_cd15					varchar(7),
${logic.hsql-only} icd_dgns_cd16					varchar(7),
${logic.hsql-only} icd_dgns_cd17					varchar(7),
${logic.hsql-only} icd_dgns_cd18					varchar(7),
${logic.hsql-only} icd_dgns_cd19					varchar(7),
${logic.hsql-only} icd_dgns_cd20					varchar(7),
${logic.hsql-only} icd_dgns_cd21					varchar(7),
${logic.hsql-only} icd_dgns_cd22					varchar(7),
${logic.hsql-only} icd_dgns_cd23					varchar(7),
${logic.hsql-only} icd_dgns_cd24					varchar(7),
${logic.hsql-only} icd_dgns_cd25					varchar(7),
${logic.hsql-only} icd_dgns_vrsn_cd1				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd2				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd3				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd4				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd5				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd6				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd7				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd8				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd9				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd10				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd11				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd12				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd13				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd14				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd15				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd16				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd17				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd18				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd19				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd20				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd21				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd22				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd23				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd24				char(1),
${logic.hsql-only} icd_dgns_vrsn_cd25				char(1),
${logic.hsql-only} icd_dgns_e_cd1					varchar(7),
${logic.hsql-only} icd_dgns_e_cd2					varchar(7),
${logic.hsql-only} icd_dgns_e_cd3					varchar(7),
${logic.hsql-only} icd_dgns_e_cd4					varchar(7),
${logic.hsql-only} icd_dgns_e_cd5					varchar(7),
${logic.hsql-only} icd_dgns_e_cd6					varchar(7),
${logic.hsql-only} icd_dgns_e_cd7					varchar(7),
${logic.hsql-only} icd_dgns_e_cd8					varchar(7),
${logic.hsql-only} icd_dgns_e_cd9					varchar(7),
${logic.hsql-only} icd_dgns_e_cd10					varchar(7),
${logic.hsql-only} icd_dgns_e_cd11					varchar(7),
${logic.hsql-only} icd_dgns_e_cd12					varchar(7),
${logic.hsql-only} icd_dgns_e_vrsn_cd1				char(1),
${logic.hsql-only} icd_dgns_e_vrsn_cd2				char(1),
${logic.hsql-only} icd_dgns_e_vrsn_cd3				char(1),
${logic.hsql-only} icd_dgns_e_vrsn_cd4				char(1),
${logic.hsql-only} icd_dgns_e_vrsn_cd5				char(1),
${logic.hsql-only} icd_dgns_e_vrsn_cd6				char(1),
${logic.hsql-only} icd_dgns_e_vrsn_cd7				char(1),
${logic.hsql-only} icd_dgns_e_vrsn_cd8				char(1),
${logic.hsql-only} icd_dgns_e_vrsn_cd9				char(1),
${logic.hsql-only} icd_dgns_e_vrsn_cd10				char(1),
${logic.hsql-only} icd_dgns_e_vrsn_cd11				char(1),
${logic.hsql-only} icd_dgns_e_vrsn_cd12				char(1),
${logic.hsql-only} icd_prcdr_cd1					varchar(7),
${logic.hsql-only} icd_prcdr_cd2					varchar(7),
${logic.hsql-only} icd_prcdr_cd3					varchar(7),
${logic.hsql-only} icd_prcdr_cd4					varchar(7),
${logic.hsql-only} icd_prcdr_cd5					varchar(7),
${logic.hsql-only} icd_prcdr_cd6					varchar(7),
${logic.hsql-only} icd_prcdr_cd7					varchar(7),
${logic.hsql-only} icd_prcdr_cd8					varchar(7),
${logic.hsql-only} icd_prcdr_cd9					varchar(7),
${logic.hsql-only} icd_prcdr_cd10					varchar(7),
${logic.hsql-only} icd_prcdr_cd11					varchar(7),
${logic.hsql-only} icd_prcdr_cd12					varchar(7),
${logic.hsql-only} icd_prcdr_cd13					varchar(7),
${logic.hsql-only} icd_prcdr_cd14					varchar(7),
${logic.hsql-only} icd_prcdr_cd15					varchar(7),
${logic.hsql-only} icd_prcdr_cd16					varchar(7),
${logic.hsql-only} icd_prcdr_cd17					varchar(7),
${logic.hsql-only} icd_prcdr_cd18					varchar(7),
${logic.hsql-only} icd_prcdr_cd19					varchar(7),
${logic.hsql-only} icd_prcdr_cd20					varchar(7),
${logic.hsql-only} icd_prcdr_cd21					varchar(7),
${logic.hsql-only} icd_prcdr_cd22					varchar(7),
${logic.hsql-only} icd_prcdr_cd23					varchar(7),
${logic.hsql-only} icd_prcdr_cd24					varchar(7),
${logic.hsql-only} icd_prcdr_cd25					varchar(7),
${logic.hsql-only} icd_prcdr_vrsn_cd1				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd2				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd3				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd4				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd5				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd6				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd7				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd8				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd9				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd10				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd11				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd12				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd13				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd14				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd15				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd16				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd17				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd18				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd19				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd20				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd21				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd22				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd23				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd24				char(1),
${logic.hsql-only} icd_prcdr_vrsn_cd25				char(1),
${logic.hsql-only} prcdr_dt1						date,
${logic.hsql-only} prcdr_dt2						date,
${logic.hsql-only} prcdr_dt3						date,
${logic.hsql-only} prcdr_dt4						date,
${logic.hsql-only} prcdr_dt5						date,
${logic.hsql-only} prcdr_dt6						date,
${logic.hsql-only} prcdr_dt7						date,
${logic.hsql-only} prcdr_dt8						date,
${logic.hsql-only} prcdr_dt9						date,
${logic.hsql-only} prcdr_dt10						date,
${logic.hsql-only} prcdr_dt11						date,
${logic.hsql-only} prcdr_dt12						date,
${logic.hsql-only} prcdr_dt13						date,
${logic.hsql-only} prcdr_dt14						date,
${logic.hsql-only} prcdr_dt15						date,
${logic.hsql-only} prcdr_dt16						date,
${logic.hsql-only} prcdr_dt17						date,
${logic.hsql-only} prcdr_dt18						date,
${logic.hsql-only} prcdr_dt19						date,
${logic.hsql-only} prcdr_dt20						date,
${logic.hsql-only} prcdr_dt21						date,
${logic.hsql-only} prcdr_dt22						date,
${logic.hsql-only} prcdr_dt23						date,
${logic.hsql-only} prcdr_dt24						date,
${logic.hsql-only} prcdr_dt25						date,
${logic.hsql-only} CONSTRAINT public.bfd1485_outpatient_claims_pkey PRIMARY KEY (clm_id));

${logic.psql-only} SET max_parallel_workers = 24;
${logic.psql-only} SET max_parallel_workers_per_gather = 20;
${logic.psql-only} SET parallel_leader_participation = off;
${logic.psql-only} SET parallel_tuple_cost = 0;
${logic.psql-only} SET parallel_setup_cost = 0;
${logic.psql-only} SET min_parallel_table_scan_size = 0;

${logic.hsql-only} insert into public.bfd1485_outpatient_claims(
${logic.hsql-only}	clm_id,
${logic.hsql-only}	bene_id,
${logic.hsql-only}	clm_grp_id,
${logic.hsql-only}	last_updated,
${logic.hsql-only}	clm_from_dt,
${logic.hsql-only}	clm_thru_dt,
${logic.hsql-only}	clm_fac_type_cd,
${logic.hsql-only}	clm_freq_cd,
${logic.hsql-only}	clm_mdcr_non_pmt_rsn_cd,
${logic.hsql-only}	clm_srvc_clsfctn_type_cd,
${logic.hsql-only}	clm_mco_pd_sw,
${logic.hsql-only}	clm_pmt_amt,
${logic.hsql-only}	clm_op_prvdr_pmt_amt,
${logic.hsql-only}	clm_tot_chrg_amt,
${logic.hsql-only}	clm_op_bene_pmt_amt,
${logic.hsql-only}	claim_query_code,
${logic.hsql-only}	at_physn_npi,
${logic.hsql-only}	at_physn_upin,
${logic.hsql-only}	nch_prmry_pyr_cd,
${logic.hsql-only}	nch_clm_type_cd,
${logic.hsql-only}	nch_near_line_rec_ident_cd,
${logic.hsql-only}	nch_wkly_proc_dt,
${logic.hsql-only}	nch_bene_blood_ddctbl_lblty_am,
${logic.hsql-only}	nch_bene_ptb_coinsrnc_amt,
${logic.hsql-only}	nch_bene_ptb_ddctbl_amt,
${logic.hsql-only}	nch_prmry_pyr_clm_pd_amt,
${logic.hsql-only}	nch_profnl_cmpnt_chrg_amt,
${logic.hsql-only}	fi_clm_proc_dt,
${logic.hsql-only}	fi_num,
${logic.hsql-only}	fi_doc_clm_cntl_num,
${logic.hsql-only}	fi_orig_clm_cntl_num,
${logic.hsql-only}	fst_dgns_e_cd,
${logic.hsql-only}	fst_dgns_e_vrsn_cd,
${logic.hsql-only}	prncpal_dgns_cd,
${logic.hsql-only}	prncpal_dgns_vrsn_cd,
${logic.hsql-only}	prvdr_num,
${logic.hsql-only}	prvdr_state_cd,
${logic.hsql-only}	org_npi_num,
${logic.hsql-only}	op_physn_npi,
${logic.hsql-only}	op_physn_upin,
${logic.hsql-only}	ot_physn_npi,
${logic.hsql-only}	ot_physn_upin,
${logic.hsql-only}	ptnt_dschrg_stus_cd,
${logic.hsql-only}	final_action,
${logic.hsql-only}	rsn_visit_cd1,
${logic.hsql-only}	rsn_visit_vrsn_cd1,
${logic.hsql-only}	rsn_visit_cd2,
${logic.hsql-only}	rsn_visit_vrsn_cd2,
${logic.hsql-only}	rsn_visit_cd3,
${logic.hsql-only}	rsn_visit_vrsn_cd3,
${logic.hsql-only}	icd_dgns_cd1,
${logic.hsql-only}	icd_dgns_cd2,
${logic.hsql-only}	icd_dgns_cd3,
${logic.hsql-only}	icd_dgns_cd4,
${logic.hsql-only}	icd_dgns_cd5,
${logic.hsql-only}	icd_dgns_cd6,
${logic.hsql-only}	icd_dgns_cd7,
${logic.hsql-only}	icd_dgns_cd8,
${logic.hsql-only}	icd_dgns_cd9,
${logic.hsql-only}	icd_dgns_cd10,
${logic.hsql-only}	icd_dgns_cd11,
${logic.hsql-only}	icd_dgns_cd12,
${logic.hsql-only}	icd_dgns_cd13,
${logic.hsql-only}	icd_dgns_cd14,
${logic.hsql-only}	icd_dgns_cd15,
${logic.hsql-only}	icd_dgns_cd16,
${logic.hsql-only}	icd_dgns_cd17,
${logic.hsql-only}	icd_dgns_cd18,
${logic.hsql-only}	icd_dgns_cd19,
${logic.hsql-only}	icd_dgns_cd20,
${logic.hsql-only}	icd_dgns_cd21,
${logic.hsql-only}	icd_dgns_cd22,
${logic.hsql-only}	icd_dgns_cd23,
${logic.hsql-only}	icd_dgns_cd24,
${logic.hsql-only}	icd_dgns_cd25,
${logic.hsql-only}	icd_dgns_vrsn_cd1,
${logic.hsql-only}	icd_dgns_vrsn_cd2,
${logic.hsql-only}	icd_dgns_vrsn_cd3,
${logic.hsql-only}	icd_dgns_vrsn_cd4,
${logic.hsql-only}	icd_dgns_vrsn_cd5,
${logic.hsql-only}	icd_dgns_vrsn_cd6,
${logic.hsql-only}	icd_dgns_vrsn_cd7,
${logic.hsql-only}	icd_dgns_vrsn_cd8,
${logic.hsql-only}	icd_dgns_vrsn_cd9,
${logic.hsql-only}	icd_dgns_vrsn_cd10,
${logic.hsql-only}	icd_dgns_vrsn_cd11,
${logic.hsql-only}	icd_dgns_vrsn_cd12,
${logic.hsql-only}	icd_dgns_vrsn_cd13,
${logic.hsql-only}	icd_dgns_vrsn_cd14,
${logic.hsql-only}	icd_dgns_vrsn_cd15,
${logic.hsql-only}	icd_dgns_vrsn_cd16,
${logic.hsql-only}	icd_dgns_vrsn_cd17,
${logic.hsql-only}	icd_dgns_vrsn_cd18,
${logic.hsql-only}	icd_dgns_vrsn_cd19,
${logic.hsql-only}	icd_dgns_vrsn_cd20,
${logic.hsql-only}	icd_dgns_vrsn_cd21,
${logic.hsql-only}	icd_dgns_vrsn_cd22,
${logic.hsql-only}	icd_dgns_vrsn_cd23,
${logic.hsql-only}	icd_dgns_vrsn_cd24,
${logic.hsql-only}	icd_dgns_vrsn_cd25,
${logic.hsql-only}	icd_dgns_e_cd1,
${logic.hsql-only}	icd_dgns_e_cd2,
${logic.hsql-only}	icd_dgns_e_cd3,
${logic.hsql-only}	icd_dgns_e_cd4,
${logic.hsql-only}	icd_dgns_e_cd5,
${logic.hsql-only}	icd_dgns_e_cd6,
${logic.hsql-only}	icd_dgns_e_cd7,
${logic.hsql-only}	icd_dgns_e_cd8,
${logic.hsql-only}	icd_dgns_e_cd9,
${logic.hsql-only}	icd_dgns_e_cd10,
${logic.hsql-only}	icd_dgns_e_cd11,
${logic.hsql-only}	icd_dgns_e_cd12,
${logic.hsql-only}	icd_dgns_e_vrsn_cd1,
${logic.hsql-only}	icd_dgns_e_vrsn_cd2,
${logic.hsql-only}	icd_dgns_e_vrsn_cd3,
${logic.hsql-only}	icd_dgns_e_vrsn_cd4,
${logic.hsql-only}	icd_dgns_e_vrsn_cd5,
${logic.hsql-only}	icd_dgns_e_vrsn_cd6,
${logic.hsql-only}	icd_dgns_e_vrsn_cd7,
${logic.hsql-only}	icd_dgns_e_vrsn_cd8,
${logic.hsql-only}	icd_dgns_e_vrsn_cd9,
${logic.hsql-only}	icd_dgns_e_vrsn_cd10,
${logic.hsql-only}	icd_dgns_e_vrsn_cd11,
${logic.hsql-only}	icd_dgns_e_vrsn_cd12,
${logic.hsql-only}	icd_prcdr_cd1,
${logic.hsql-only}	icd_prcdr_cd2,
${logic.hsql-only}	icd_prcdr_cd3,
${logic.hsql-only}	icd_prcdr_cd4,
${logic.hsql-only}	icd_prcdr_cd5,
${logic.hsql-only}	icd_prcdr_cd6,
${logic.hsql-only}	icd_prcdr_cd7,
${logic.hsql-only}	icd_prcdr_cd8,
${logic.hsql-only}	icd_prcdr_cd9,
${logic.hsql-only}	icd_prcdr_cd10,
${logic.hsql-only}	icd_prcdr_cd11,
${logic.hsql-only}	icd_prcdr_cd12,
${logic.hsql-only}	icd_prcdr_cd13,
${logic.hsql-only}	icd_prcdr_cd14,
${logic.hsql-only}	icd_prcdr_cd15,
${logic.hsql-only}	icd_prcdr_cd16,
${logic.hsql-only}	icd_prcdr_cd17,
${logic.hsql-only}	icd_prcdr_cd18,
${logic.hsql-only}	icd_prcdr_cd19,
${logic.hsql-only}	icd_prcdr_cd20,
${logic.hsql-only}	icd_prcdr_cd21,
${logic.hsql-only}	icd_prcdr_cd22,
${logic.hsql-only}	icd_prcdr_cd23,
${logic.hsql-only}	icd_prcdr_cd24,
${logic.hsql-only}	icd_prcdr_cd25,
${logic.hsql-only}	icd_prcdr_vrsn_cd1,
${logic.hsql-only}	icd_prcdr_vrsn_cd2,
${logic.hsql-only}	icd_prcdr_vrsn_cd3,
${logic.hsql-only}	icd_prcdr_vrsn_cd4,
${logic.hsql-only}	icd_prcdr_vrsn_cd5,
${logic.hsql-only}	icd_prcdr_vrsn_cd6,
${logic.hsql-only}	icd_prcdr_vrsn_cd7,
${logic.hsql-only}	icd_prcdr_vrsn_cd8,
${logic.hsql-only}	icd_prcdr_vrsn_cd9,
${logic.hsql-only}	icd_prcdr_vrsn_cd10,
${logic.hsql-only}	icd_prcdr_vrsn_cd11,
${logic.hsql-only}	icd_prcdr_vrsn_cd12,
${logic.hsql-only}	icd_prcdr_vrsn_cd13,
${logic.hsql-only}	icd_prcdr_vrsn_cd14,
${logic.hsql-only}	icd_prcdr_vrsn_cd15,
${logic.hsql-only}	icd_prcdr_vrsn_cd16,
${logic.hsql-only}	icd_prcdr_vrsn_cd17,
${logic.hsql-only}	icd_prcdr_vrsn_cd18,
${logic.hsql-only}	icd_prcdr_vrsn_cd19,
${logic.hsql-only}	icd_prcdr_vrsn_cd20,
${logic.hsql-only}	icd_prcdr_vrsn_cd21,
${logic.hsql-only}	icd_prcdr_vrsn_cd22,
${logic.hsql-only}	icd_prcdr_vrsn_cd23,
${logic.hsql-only}	icd_prcdr_vrsn_cd24,
${logic.hsql-only}	icd_prcdr_vrsn_cd25,
${logic.hsql-only}	prcdr_dt1,
${logic.hsql-only}	prcdr_dt2,
${logic.hsql-only}	prcdr_dt3,
${logic.hsql-only}	prcdr_dt4,
${logic.hsql-only}	prcdr_dt5,
${logic.hsql-only}	prcdr_dt6,
${logic.hsql-only}	prcdr_dt7,
${logic.hsql-only}	prcdr_dt8,
${logic.hsql-only}	prcdr_dt9,
${logic.hsql-only}	prcdr_dt10,
${logic.hsql-only}	prcdr_dt11,
${logic.hsql-only}	prcdr_dt12,
${logic.hsql-only}	prcdr_dt13,
${logic.hsql-only}	prcdr_dt14,
${logic.hsql-only}	prcdr_dt15,
${logic.hsql-only}	prcdr_dt16,
${logic.hsql-only}	prcdr_dt17,
${logic.hsql-only}	prcdr_dt18,
${logic.hsql-only}	prcdr_dt19,
${logic.hsql-only}	prcdr_dt20,
${logic.hsql-only}	prcdr_dt21,
${logic.hsql-only}	prcdr_dt22,
${logic.hsql-only}	prcdr_dt23,
${logic.hsql-only}	prcdr_dt24,
${logic.hsql-only}	prcdr_dt25
${logic.hsql-only} )
${logic.psql-only} create table public.bfd1485_outpatient_claims as
select
	${logic.psql-only} cast(clm_id as bigint),
	${logic.psql-only} cast(bene_id as bigint),
	${logic.psql-only} cast(clm_grp_id as bigint),  
    ${logic.hsql-only} convert(clm_id, SQL_BIGINT),
	${logic.hsql-only} convert(bene_id, SQL_BIGINT),
	${logic.hsql-only} convert(clm_grp_id, SQL_BIGINT),
	last_updated,
	clm_from_dt,
	clm_thru_dt,
	clm_fac_type_cd,
	clm_freq_cd,
	clm_mdcr_non_pmt_rsn_cd,
	clm_srvc_clsfctn_type_cd,
	clm_mco_pd_sw,
	${logic.psql-only} cast(clm_pmt_amt as numeric(10,2)),
	${logic.hsql-only} clm_pmt_amt,
	${logic.psql-only} cast(clm_op_prvdr_pmt_amt as numeric(10,2)),
	${logic.hsql-only} clm_op_prvdr_pmt_amt,
	${logic.psql-only} cast(clm_tot_chrg_amt as numeric(10,2)),
	${logic.hsql-only} clm_tot_chrg_amt,
	${logic.psql-only} cast(clm_op_bene_pmt_amt as numeric(10,2)),
	${logic.hsql-only} clm_op_bene_pmt_amt,
	claim_query_code,
	at_physn_npi,
	at_physn_upin,
	nch_prmry_pyr_cd,
	nch_clm_type_cd,
	nch_near_line_rec_ident_cd,
	nch_wkly_proc_dt,
	${logic.psql-only} cast(nch_bene_blood_ddctbl_lblty_am as numeric(10,2)),
	${logic.hsql-only} nch_bene_blood_ddctbl_lblty_am,
	${logic.psql-only} cast(nch_bene_ptb_coinsrnc_amt as numeric(10,2)),
	${logic.hsql-only} nch_bene_ptb_coinsrnc_amt,
	${logic.psql-only} cast(nch_bene_ptb_ddctbl_amt as numeric(10,2)),
	${logic.hsql-only} nch_bene_ptb_ddctbl_amt,
	${logic.psql-only} cast(nch_prmry_pyr_clm_pd_amt as numeric(10,2)),
	${logic.hsql-only} nch_prmry_pyr_clm_pd_amt,
	${logic.psql-only} cast(nch_profnl_cmpnt_chrg_amt as numeric(10,2)),
	${logic.hsql-only} nch_profnl_cmpnt_chrg_amt,
	fi_clm_proc_dt,
	fi_num,
	fi_doc_clm_cntl_num,
	fi_orig_clm_cntl_num,
	fst_dgns_e_cd,
	fst_dgns_e_vrsn_cd,
	prncpal_dgns_cd,
	prncpal_dgns_vrsn_cd,
	prvdr_num,
	prvdr_state_cd,
	org_npi_num,
	op_physn_npi,
	op_physn_upin,
	ot_physn_npi,
	ot_physn_upin,
	ptnt_dschrg_stus_cd,
	final_action,
	rsn_visit_cd1,
	rsn_visit_vrsn_cd1,
	rsn_visit_cd2,
	rsn_visit_vrsn_cd2,
	rsn_visit_cd3,
	rsn_visit_vrsn_cd3,
	icd_dgns_cd1,
	icd_dgns_cd2,
	icd_dgns_cd3,
	icd_dgns_cd4,
	icd_dgns_cd5,
	icd_dgns_cd6,
	icd_dgns_cd7,
	icd_dgns_cd8,
	icd_dgns_cd9,
	icd_dgns_cd10,
	icd_dgns_cd11,
	icd_dgns_cd12,
	icd_dgns_cd13,
	icd_dgns_cd14,
	icd_dgns_cd15,
	icd_dgns_cd16,
	icd_dgns_cd17,
	icd_dgns_cd18,
	icd_dgns_cd19,
	icd_dgns_cd20,
	icd_dgns_cd21,
	icd_dgns_cd22,
	icd_dgns_cd23,
	icd_dgns_cd24,
	icd_dgns_cd25,
	icd_dgns_vrsn_cd1,
	icd_dgns_vrsn_cd2,
	icd_dgns_vrsn_cd3,
	icd_dgns_vrsn_cd4,
	icd_dgns_vrsn_cd5,
	icd_dgns_vrsn_cd6,
	icd_dgns_vrsn_cd7,
	icd_dgns_vrsn_cd8,
	icd_dgns_vrsn_cd9,
	icd_dgns_vrsn_cd10,
	icd_dgns_vrsn_cd11,
	icd_dgns_vrsn_cd12,
	icd_dgns_vrsn_cd13,
	icd_dgns_vrsn_cd14,
	icd_dgns_vrsn_cd15,
	icd_dgns_vrsn_cd16,
	icd_dgns_vrsn_cd17,
	icd_dgns_vrsn_cd18,
	icd_dgns_vrsn_cd19,
	icd_dgns_vrsn_cd20,
	icd_dgns_vrsn_cd21,
	icd_dgns_vrsn_cd22,
	icd_dgns_vrsn_cd23,
	icd_dgns_vrsn_cd24,
	icd_dgns_vrsn_cd25,
	icd_dgns_e_cd1,
	icd_dgns_e_cd2,
	icd_dgns_e_cd3,
	icd_dgns_e_cd4,
	icd_dgns_e_cd5,
	icd_dgns_e_cd6,
	icd_dgns_e_cd7,
	icd_dgns_e_cd8,
	icd_dgns_e_cd9,
	icd_dgns_e_cd10,
	icd_dgns_e_cd11,
	icd_dgns_e_cd12,
	icd_dgns_e_vrsn_cd1,
	icd_dgns_e_vrsn_cd2,
	icd_dgns_e_vrsn_cd3,
	icd_dgns_e_vrsn_cd4,
	icd_dgns_e_vrsn_cd5,
	icd_dgns_e_vrsn_cd6,
	icd_dgns_e_vrsn_cd7,
	icd_dgns_e_vrsn_cd8,
	icd_dgns_e_vrsn_cd9,
	icd_dgns_e_vrsn_cd10,
	icd_dgns_e_vrsn_cd11,
	icd_dgns_e_vrsn_cd12,
	icd_prcdr_cd1,
	icd_prcdr_cd2,
	icd_prcdr_cd3,
	icd_prcdr_cd4,
	icd_prcdr_cd5,
	icd_prcdr_cd6,
	icd_prcdr_cd7,
	icd_prcdr_cd8,
	icd_prcdr_cd9,
	icd_prcdr_cd10,
	icd_prcdr_cd11,
	icd_prcdr_cd12,
	icd_prcdr_cd13,
	icd_prcdr_cd14,
	icd_prcdr_cd15,
	icd_prcdr_cd16,
	icd_prcdr_cd17,
	icd_prcdr_cd18,
	icd_prcdr_cd19,
	icd_prcdr_cd20,
	icd_prcdr_cd21,
	icd_prcdr_cd22,
	icd_prcdr_cd23,
	icd_prcdr_cd24,
	icd_prcdr_cd25,
	icd_prcdr_vrsn_cd1,
	icd_prcdr_vrsn_cd2,
	icd_prcdr_vrsn_cd3,
	icd_prcdr_vrsn_cd4,
	icd_prcdr_vrsn_cd5,
	icd_prcdr_vrsn_cd6,
	icd_prcdr_vrsn_cd7,
	icd_prcdr_vrsn_cd8,
	icd_prcdr_vrsn_cd9,
	icd_prcdr_vrsn_cd10,
	icd_prcdr_vrsn_cd11,
	icd_prcdr_vrsn_cd12,
	icd_prcdr_vrsn_cd13,
	icd_prcdr_vrsn_cd14,
	icd_prcdr_vrsn_cd15,
	icd_prcdr_vrsn_cd16,
	icd_prcdr_vrsn_cd17,
	icd_prcdr_vrsn_cd18,
	icd_prcdr_vrsn_cd19,
	icd_prcdr_vrsn_cd20,
	icd_prcdr_vrsn_cd21,
	icd_prcdr_vrsn_cd22,
	icd_prcdr_vrsn_cd23,
	icd_prcdr_vrsn_cd24,
	icd_prcdr_vrsn_cd25,
	prcdr_dt1,
	prcdr_dt2,
	prcdr_dt3,
	prcdr_dt4,
	prcdr_dt5,
	prcdr_dt6,
	prcdr_dt7,
	prcdr_dt8,
	prcdr_dt9,
	prcdr_dt10,
	prcdr_dt11,
	prcdr_dt12,
	prcdr_dt13,
	prcdr_dt14,
	prcdr_dt15,
	prcdr_dt16,
	prcdr_dt17,
	prcdr_dt18,
	prcdr_dt19,
	prcdr_dt20,
	prcdr_dt21,
	prcdr_dt22,
	prcdr_dt23,
	prcdr_dt24,
	prcdr_dt25
from
	public.outpatient_claims;

${logic.psql-only} alter table public.bfd1485_outpatient_claims
${logic.psql-only}     alter column clm_id SET NOT NULL,
${logic.psql-only}     alter column bene_id SET NOT NULL,
${logic.psql-only}     alter column clm_grp_id SET NOT NULL,
${logic.psql-only}     alter column clm_op_bene_pmt_amt SET NOT NULL,
${logic.psql-only}     alter column nch_bene_blood_ddctbl_lblty_am SET NOT NULL,
${logic.psql-only}     alter column clm_fac_type_cd SET NOT NULL,
${logic.psql-only}     alter column clm_freq_cd SET NOT NULL,
${logic.psql-only}     alter column claim_query_code SET NOT NULL,
${logic.psql-only}     alter column clm_srvc_clsfctn_type_cd SET NOT NULL,
${logic.psql-only}     alter column nch_clm_type_cd SET NOT NULL,
${logic.psql-only}     alter column nch_bene_ptb_coinsrnc_amt SET NOT NULL,
${logic.psql-only}     alter column clm_from_dt SET NOT NULL,
${logic.psql-only}     alter column clm_thru_dt SET NOT NULL,
${logic.psql-only}     alter column nch_bene_ptb_ddctbl_amt SET NOT NULL,
${logic.psql-only}     alter column nch_near_line_rec_ident_cd SET NOT NULL,
${logic.psql-only}     alter column clm_pmt_amt SET NOT NULL,
${logic.psql-only}     alter column nch_prmry_pyr_clm_pd_amt SET NOT NULL,
${logic.psql-only}     alter column nch_profnl_cmpnt_chrg_amt SET NOT NULL,
${logic.psql-only}     alter column prvdr_num SET NOT NULL,
${logic.psql-only}     alter column clm_op_prvdr_pmt_amt SET NOT NULL,
${logic.psql-only}     alter column prvdr_state_cd SET NOT NULL,
${logic.psql-only}     alter column clm_tot_chrg_amt SET NOT NULL,
${logic.psql-only}     alter column nch_wkly_proc_dt SET NOT NULL,
${logic.psql-only}     alter column final_action SET NOT NULL;

${logic.psql-only} alter table public.bfd1485_outpatient_claims
${logic.psql-only}     add CONSTRAINT bfd1485_outpatient_claims_pkey PRIMARY KEY (clm_id);

CREATE INDEX IF NOT EXISTS bfd1485_outpatient_claims_bene_id_idx
	ON public.bfd1485_outpatient_claims (bene_id);