${logic.hsql-only} CREATE TABLE IF NOT EXISTS public.bfd1485_outpatient_claim_lines (
${logic.hsql-only} 	clm_id 								bigint NOT NULL,
${logic.hsql-only} 	clm_line_num						smallint NOT NULL,
${logic.hsql-only} 	rev_cntr							varchar(4)  NOT NULL,
${logic.hsql-only} 	rev_cntr_dt							date,
${logic.hsql-only} 	rev_cntr_dscnt_ind_cd				char(1),
${logic.hsql-only} 	rev_cntr_stus_ind_cd				varchar(2),
${logic.hsql-only} 	rev_cntr_unit_cnt					integer NOT NULL,
${logic.hsql-only} 	rev_cntr_ndc_qty					integer,
${logic.hsql-only} 	rev_cntr_ide_ndc_upc_num			varchar(24),
${logic.hsql-only} 	rev_cntr_ndc_qty_qlfr_cd			varchar(2),
${logic.hsql-only} 	rev_cntr_otaf_pmt_cd				char(1),
${logic.hsql-only} 	rev_cntr_packg_ind_cd				char(1),
${logic.hsql-only} 	rev_cntr_apc_hipps_cd				varchar(5),
${logic.hsql-only} 	rev_cntr_1st_ansi_cd				varchar(5),
${logic.hsql-only} 	rev_cntr_2nd_ansi_cd				varchar(5),
${logic.hsql-only} 	rev_cntr_3rd_ansi_cd				varchar(5),
${logic.hsql-only} 	rev_cntr_4th_ansi_cd				varchar(5),
${logic.hsql-only} 	rev_cntr_pmt_mthd_ind_cd			varchar(2),
${logic.hsql-only} 	rev_cntr_tot_chrg_amt			 	numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_pmt_amt_amt				numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_rate_amt			 		numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_prvdr_pmt_amt			 	numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_bene_pmt_amt				numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_ptnt_rspnsblty_pmt			numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_blood_ddctbl_amt			numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_cash_ddctbl_amt			numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_1st_msp_pd_amt			 	numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_2nd_msp_pd_amt			 	numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_ncvrd_chrg_amt				numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_rdcd_coinsrnc_amt			numeric(10,2) NOT NULL,
${logic.hsql-only} 	rev_cntr_coinsrnc_wge_adjstd_c		numeric(10,2) NOT NULL,
${logic.hsql-only} 	hcpcs_cd							varchar(5),
${logic.hsql-only} 	hcpcs_1st_mdfr_cd					varchar(5),
${logic.hsql-only} 	hcpcs_2nd_mdfr_cd					varchar(5),
${logic.hsql-only} 	rndrng_physn_npi					varchar(12),
${logic.hsql-only} 	rndrng_physn_upin					varchar(12),
${logic.hsql-only} 	CONSTRAINT bfd1485_outpatient_claim_lines_pkey PRIMARY KEY (clm_id, clm_line_num));

${logic.psql-only} SET max_parallel_workers = 24;
${logic.psql-only} SET max_parallel_workers_per_gather = 20;
${logic.psql-only} SET parallel_leader_participation = off;
${logic.psql-only} SET parallel_tuple_cost = 0;
${logic.psql-only} SET parallel_setup_cost = 0;
${logic.psql-only} SET min_parallel_table_scan_size = 0;

${logic.hsql-only} insert into public.bfd1485_outpatient_claim_lines(
${logic.hsql-only}	clm_id,
${logic.hsql-only}	clm_line_num,
${logic.hsql-only}	rev_cntr,
${logic.hsql-only}	rev_cntr_dt,
${logic.hsql-only}	rev_cntr_dscnt_ind_cd,
${logic.hsql-only}	rev_cntr_stus_ind_cd,
${logic.hsql-only}	rev_cntr_unit_cnt,
${logic.hsql-only}	rev_cntr_ndc_qty,
${logic.hsql-only}	rev_cntr_ide_ndc_upc_num,
${logic.hsql-only}	rev_cntr_ndc_qty_qlfr_cd,
${logic.hsql-only}	rev_cntr_otaf_pmt_cd,
${logic.hsql-only}	rev_cntr_packg_ind_cd,
${logic.hsql-only}	rev_cntr_apc_hipps_cd,
${logic.hsql-only}	rev_cntr_1st_ansi_cd,
${logic.hsql-only}	rev_cntr_2nd_ansi_cd,
${logic.hsql-only}	rev_cntr_3rd_ansi_cd,
${logic.hsql-only}	rev_cntr_4th_ansi_cd,
${logic.hsql-only}	rev_cntr_pmt_mthd_ind_cd,
${logic.hsql-only}	rev_cntr_tot_chrg_amt,
${logic.hsql-only}	rev_cntr_pmt_amt_amt,
${logic.hsql-only}	rev_cntr_rate_amt,
${logic.hsql-only}	rev_cntr_prvdr_pmt_amt,
${logic.hsql-only}	rev_cntr_bene_pmt_amt,
${logic.hsql-only}	rev_cntr_ptnt_rspnsblty_pmt,
${logic.hsql-only}	rev_cntr_blood_ddctbl_amt,
${logic.hsql-only}	rev_cntr_cash_ddctbl_amt,
${logic.hsql-only}	rev_cntr_1st_msp_pd_amt,
${logic.hsql-only}	rev_cntr_2nd_msp_pd_amt,
${logic.hsql-only}	rev_cntr_ncvrd_chrg_amt,
${logic.hsql-only}	rev_cntr_rdcd_coinsrnc_amt,
${logic.hsql-only}	rev_cntr_coinsrnc_wge_adjstd_c,
${logic.hsql-only}	hcpcs_cd,
${logic.hsql-only}	hcpcs_1st_mdfr_cd,
${logic.hsql-only}	hcpcs_2nd_mdfr_cd,
${logic.hsql-only}	rndrng_physn_npi,
${logic.hsql-only}	rndrng_physn_upin )
${logic.psql-only} create table public.bfd1485_outpatient_claim_lines as
select
	${logic.psql-only} cast(clm_id as bigint),  
    ${logic.hsql-only} convert(clm_id, SQL_BIGINT),
	${logic.psql-only} cast(clm_line_num as smallint),
	${logic.hsql-only} convert(clm_line_num, SQL_SMALLINT),
    rev_cntr,
    rev_cntr_dt,
    rev_cntr_dscnt_ind_cd,
    rev_cntr_stus_ind_cd,
    rev_cntr_unit_cnt,
    ${logic.psql-only} cast(rev_cntr_ndc_qty as integer),
	${logic.hsql-only} rev_cntr_ndc_qty,
    rev_cntr_ide_ndc_upc_num,
    rev_cntr_ndc_qty_qlfr_cd,
    rev_cntr_otaf_pmt_cd,
    rev_cntr_packg_ind_cd,
    rev_cntr_apc_hipps_cd,
    rev_cntr_1st_ansi_cd,
    rev_cntr_2nd_ansi_cd,
    rev_cntr_3rd_ansi_cd,
    rev_cntr_4th_ansi_cd,
    rev_cntr_pmt_mthd_ind_cd,
    ${logic.psql-only} cast(rev_cntr_tot_chrg_amt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_tot_chrg_amt,
    ${logic.psql-only} cast(rev_cntr_pmt_amt_amt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_pmt_amt_amt,
    ${logic.psql-only} cast(rev_cntr_rate_amt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_rate_amt,
    ${logic.psql-only} cast(rev_cntr_prvdr_pmt_amt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_prvdr_pmt_amt,
    ${logic.psql-only} cast(rev_cntr_bene_pmt_amt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_bene_pmt_amt,
    ${logic.psql-only} cast(rev_cntr_ptnt_rspnsblty_pmt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_ptnt_rspnsblty_pmt,
    ${logic.psql-only} cast(rev_cntr_blood_ddctbl_amt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_blood_ddctbl_amt,
    ${logic.psql-only} cast(rev_cntr_cash_ddctbl_amt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_cash_ddctbl_amt,
    ${logic.psql-only} cast(rev_cntr_1st_msp_pd_amt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_1st_msp_pd_amt,
    ${logic.psql-only} cast(rev_cntr_2nd_msp_pd_amt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_2nd_msp_pd_amt,
    ${logic.psql-only} cast(rev_cntr_ncvrd_chrg_amt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_ncvrd_chrg_amt,
    ${logic.psql-only} cast(rev_cntr_rdcd_coinsrnc_amt as numeric(10,2)),
	${logic.hsql-only} rev_cntr_rdcd_coinsrnc_amt,
    rev_cntr_coinsrnc_wge_adjstd_c,
    hcpcs_cd,
    hcpcs_1st_mdfr_cd,
    hcpcs_2nd_mdfr_cd,
    rndrng_physn_npi,
    rndrng_physn_upin
from
	public.outpatient_claim_lines;

${logic.psql-only} alter table public.bfd1485_outpatient_claim_lines
${logic.psql-only} 	alter column clm_id SET NOT NULL,
${logic.psql-only} 	alter column clm_line_num SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_unit_cnt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_tot_chrg_amt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_pmt_amt_amt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_rate_amt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_prvdr_pmt_amt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_bene_pmt_amt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_ptnt_rspnsblty_pmt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_blood_ddctbl_amt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_cash_ddctbl_amt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_1st_msp_pd_amt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_2nd_msp_pd_amt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_ncvrd_chrg_amt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_rdcd_coinsrnc_amt SET NOT NULL,
${logic.psql-only} 	alter column rev_cntr_coinsrnc_wge_adjstd_c SET NOT NULL;

${logic.psql-only} alter table public.bfd1485_outpatient_claim_lines
${logic.psql-only}     add CONSTRAINT bfd1485_outpatient_claim_lines_pkey PRIMARY KEY (clm_id, clm_line_num);

ALTER TABLE IF EXISTS public.bfd1485_outpatient_claim_lines
    ADD CONSTRAINT bfd1485_outpatient_claim_lines_clm_id_to_outpatient_claims FOREIGN KEY (clm_id)
    	REFERENCES public.bfd1485_outpatient_claims (clm_id);