${logic.hsql-only} CREATE TABLE IF NOT EXISTS public.bfd1485_carrier_claim_lines (
${logic.hsql-only} clm_id				 			bigint not null,
${logic.hsql-only} line_num				 			smallint not null,
${logic.hsql-only} line_nch_pmt_amt					numeric(10,2) not null,
${logic.hsql-only} line_1st_expns_dt 				date,
${logic.hsql-only} line_alowd_chrg_amt				numeric(10,2) not null,
${logic.hsql-only} line_bene_pmt_amt				numeric(10,2) not null,
${logic.hsql-only} line_bene_prmry_pyr_cd			character(1),
${logic.hsql-only} line_bene_prmry_pyr_pd_amt		numeric(10,2) not null,
${logic.hsql-only} line_bene_ptb_ddctbl_amt			numeric(10,2) not null,
${logic.hsql-only} line_cms_type_srvc_cd			character(1) not null,
${logic.hsql-only} line_coinsrnc_amt				numeric(10,2) not null,
${logic.hsql-only} line_hct_hgb_rslt_num			numeric(4,1) not null,
${logic.hsql-only} line_hct_hgb_type_cd				character varying(2),
${logic.hsql-only} line_icd_dgns_cd					character varying(7),
${logic.hsql-only} line_icd_dgns_vrsn_cd			character(1),
${logic.hsql-only} line_last_expns_dt 				date,
${logic.hsql-only} line_ndc_cd				  		character varying(11),
${logic.hsql-only} line_place_of_srvc_cd			character varying(2) not null,
${logic.hsql-only} line_pmt_80_100_cd				character(1),
${logic.hsql-only} line_prcsg_ind_cd				character varying(2),
${logic.hsql-only} line_sbmtd_chrg_amt				numeric(10,2) not null,
${logic.hsql-only} line_prvdr_pmt_amt				numeric(10,2) not null,
${logic.hsql-only} line_service_deductible			character(1),
${logic.hsql-only} line_srvc_cnt				 	smallint not null,
${logic.hsql-only} carr_line_mtus_cd				character(1),
${logic.hsql-only} carr_line_mtus_cnt				integer not null,
${logic.hsql-only} betos_cd				  			character varying(3),
${logic.hsql-only} carr_line_ansthsa_unit_cnt		smallint,
${logic.hsql-only} carr_line_clia_lab_num			character varying(10),
${logic.hsql-only} carr_line_prcng_lclty_cd			character varying(2) not null,
${logic.hsql-only} carr_line_prvdr_type_cd			character(1),
${logic.hsql-only} carr_line_rdcd_pmt_phys_astn_c	character(1),
${logic.hsql-only} carr_line_rx_num					character varying(30),
${logic.hsql-only} carr_prfrng_pin_num				character varying(15) not null,
${logic.hsql-only} hcpcs_1st_mdfr_cd				character varying(5),
${logic.hsql-only} hcpcs_2nd_mdfr_cd				character varying(5),
${logic.hsql-only} hcpcs_cd				  			character varying(5),
${logic.hsql-only} hpsa_scrcty_ind_cd				character(1),
${logic.hsql-only} org_npi_num				  		character varying(10),
${logic.hsql-only} prf_physn_npi				  	character varying(12),
${logic.hsql-only} prf_physn_upin				  	character varying(12),
${logic.hsql-only} prtcptng_ind_cd				  	character(1),
${logic.hsql-only} prvdr_spclty				  		character varying(3),
${logic.hsql-only} prvdr_state_cd				  	character varying(2),
${logic.hsql-only} prvdr_zip				  		character varying(9),
${logic.hsql-only} tax_num				  			character varying(10),
${logic.hsql-only} constraint public.bfd1485_carrier_claim_lines_pkey
${logic.hsql-only}   primary key (clm_id, line_num));

${logic.psql-only} SET max_parallel_workers = 24;
${logic.psql-only} SET max_parallel_workers_per_gather = 20;
${logic.psql-only} SET parallel_leader_participation = off;
${logic.psql-only} SET parallel_tuple_cost = 0;
${logic.psql-only} SET parallel_setup_cost = 0;
${logic.psql-only} SET min_parallel_table_scan_size = 0;

${logic.hsql-only} insert into public.bfd1485_carrier_claim_lines(
${logic.hsql-only} clm_id,
${logic.hsql-only} line_num,
${logic.hsql-only} line_nch_pmt_amt,
${logic.hsql-only} line_1st_expns_dt,
${logic.hsql-only} line_alowd_chrg_amt,
${logic.hsql-only} line_bene_pmt_amt,
${logic.hsql-only} line_bene_prmry_pyr_cd,
${logic.hsql-only} line_bene_prmry_pyr_pd_amt,
${logic.hsql-only} line_bene_ptb_ddctbl_amt,
${logic.hsql-only} line_cms_type_srvc_cd,
${logic.hsql-only} line_coinsrnc_amt,
${logic.hsql-only} line_hct_hgb_rslt_num,
${logic.hsql-only} line_hct_hgb_type_cd,
${logic.hsql-only} line_icd_dgns_cd,
${logic.hsql-only} line_icd_dgns_vrsn_cd,
${logic.hsql-only} line_last_expns_dt,
${logic.hsql-only} line_ndc_cd,
${logic.hsql-only} line_place_of_srvc_cd,
${logic.hsql-only} line_pmt_80_100_cd,
${logic.hsql-only} line_prcsg_ind_cd,
${logic.hsql-only} line_sbmtd_chrg_amt,
${logic.hsql-only} line_prvdr_pmt_amt,
${logic.hsql-only} line_service_deductible,
${logic.hsql-only} line_srvc_cnt,
${logic.hsql-only} carr_line_mtus_cd,
${logic.hsql-only} carr_line_mtus_cnt,
${logic.hsql-only} betos_cd,
${logic.hsql-only} carr_line_ansthsa_unit_cnt,
${logic.hsql-only} carr_line_clia_lab_num,
${logic.hsql-only} carr_line_prcng_lclty_cd,
${logic.hsql-only} carr_line_prvdr_type_cd,
${logic.hsql-only} carr_line_rdcd_pmt_phys_astn_c,
${logic.hsql-only} carr_line_rx_num,
${logic.hsql-only} carr_prfrng_pin_num,
${logic.hsql-only} hcpcs_1st_mdfr_cd,
${logic.hsql-only} hcpcs_2nd_mdfr_cd,
${logic.hsql-only} hcpcs_cd,
${logic.hsql-only} hpsa_scrcty_ind_cd,
${logic.hsql-only} org_npi_num,
${logic.hsql-only} prf_physn_npi,
${logic.hsql-only} prf_physn_upin,
${logic.hsql-only} prtcptng_ind_cd,
${logic.hsql-only} prvdr_spclty,
${logic.hsql-only} prvdr_state_cd,
${logic.hsql-only} prvdr_zip,
${logic.hsql-only} tax_num )
--
${logic.psql-only} create table public.bfd1485_carrier_claim_lines as
select
	${logic.psql-only} cast(clm_id as bigint),  
    ${logic.hsql-only} convert(clm_id, SQL_BIGINT),
	${logic.psql-only} cast(line_num as smallint),
	${logic.hsql-only} convert(line_num, SQL_SMALLINT),
	${logic.psql-only} cast(line_nch_pmt_amt as numeric(10,2)),
	${logic.hsql-only} line_nch_pmt_amt,
	line_1st_expns_dt,
	${logic.psql-only} cast(line_alowd_chrg_amt as numeric(10,2)),
	${logic.hsql-only} line_alowd_chrg_amt,
	${logic.psql-only} cast(line_bene_pmt_amt as numeric(10,2)),
	${logic.hsql-only} line_bene_pmt_amt,
	line_bene_prmry_pyr_cd,
	${logic.psql-only} cast(line_bene_prmry_pyr_pd_amt as numeric(10,2)),
	${logic.hsql-only} line_bene_prmry_pyr_pd_amt,
	${logic.psql-only} cast(line_bene_ptb_ddctbl_amt as numeric(10,2)),
	${logic.hsql-only} line_bene_ptb_ddctbl_amt,
	line_cms_type_srvc_cd,
	${logic.psql-only} cast(line_coinsrnc_amt as numeric(10,2)),
	${logic.hsql-only} line_coinsrnc_amt,
	${logic.psql-only} cast(line_hct_hgb_rslt_num as numeric(4,1)),
	${logic.hsql-only} line_hct_hgb_rslt_num,
	line_hct_hgb_type_cd,
	line_icd_dgns_cd,
	line_icd_dgns_vrsn_cd,
	line_last_expns_dt,
	line_ndc_cd,
	line_place_of_srvc_cd,
	line_pmt_80_100_cd,
	line_prcsg_ind_cd,
	${logic.psql-only} cast(line_sbmtd_chrg_amt as numeric(10,2)),
	${logic.hsql-only} line_sbmtd_chrg_amt,
	${logic.psql-only} cast(line_prvdr_pmt_amt as numeric(10,2)),
	${logic.hsql-only} line_prvdr_pmt_amt,
	line_service_deductible,
	${logic.psql-only} cast(line_srvc_cnt as smallint),
	${logic.hsql-only} convert(line_srvc_cnt, SQL_SMALLINT),
	carr_line_mtus_cd,
	${logic.psql-only} cast(carr_line_mtus_cnt as integer),
	${logic.hsql-only} carr_line_mtus_cnt,
	betos_cd,
	${logic.psql-only} cast(carr_line_ansthsa_unit_cnt as smallint),
	${logic.hsql-only} carr_line_ansthsa_unit_cnt,
	carr_line_clia_lab_num,
	carr_line_prcng_lclty_cd,
	carr_line_prvdr_type_cd ,
	carr_line_rdcd_pmt_phys_astn_c,
	carr_line_rx_num,
	carr_prfrng_pin_num,
	hcpcs_1st_mdfr_cd,
	hcpcs_2nd_mdfr_cd,
	hcpcs_cd,
	hpsa_scrcty_ind_cd,
	org_npi_num,
	prf_physn_npi,
	prf_physn_upin,
	prtcptng_ind_cd,
	prvdr_spclty,
	prvdr_state_cd,
	prvdr_zip,
	tax_num
from
	public.carrier_claim_lines;

${logic.psql-only} alter table public.bfd1485_carrier_claim_lines
${logic.psql-only}    alter column clm_id SET NOT NULL,
${logic.psql-only}    alter column line_num	SET NOT NULL,
${logic.psql-only}    alter column line_nch_pmt_amt SET NOT NULL,
${logic.psql-only}    alter column line_alowd_chrg_amt SET NOT NULL,
${logic.psql-only}    alter column line_bene_pmt_amt SET NOT NULL,
${logic.psql-only}    alter column line_bene_prmry_pyr_pd_amt SET NOT NULL,
${logic.psql-only}    alter column line_bene_ptb_ddctbl_amt SET NOT NULL,
${logic.psql-only}    alter column line_cms_type_srvc_cd SET NOT NULL,
${logic.psql-only}    alter column line_coinsrnc_amt SET NOT NULL,
${logic.psql-only}    alter column line_hct_hgb_rslt_num SET NOT NULL,
${logic.psql-only}    alter column line_place_of_srvc_cd SET NOT NULL,
${logic.psql-only}    alter column line_sbmtd_chrg_amt SET NOT NULL,
${logic.psql-only}    alter column line_prvdr_pmt_amt SET NOT NULL,
${logic.psql-only}    alter column line_srvc_cnt SET NOT NULL,
${logic.psql-only}    alter column carr_line_mtus_cnt SET NOT NULL,
${logic.psql-only}    alter column carr_line_prcng_lclty_cd	SET NOT NULL,
${logic.psql-only}    alter column carr_prfrng_pin_num SET NOT NULL;

${logic.psql-only} alter table public.bfd1485_carrier_claim_lines
${logic.psql-only}     add CONSTRAINT bfd1485_carrier_claim_lines_pkey PRIMARY KEY (clm_id, line_num);

ALTER TABLE IF EXISTS public.bfd1485_carrier_claim_lines
    ADD CONSTRAINT bfd1485_carrier_claim_lines_clm_id_to_carrier_claims FOREIGN KEY (clm_id)
    	REFERENCES public.bfd1485_carrier_claims (clm_id);