${logic.hsql-only}	CREATE TABLE IF NOT EXISTS public.bfd1485_dme_claim_lines (
${logic.hsql-only}	clm_id							bigint NOT NULL,
${logic.hsql-only}	line_num						smallint NOT NULL,
${logic.hsql-only}	line_srvc_cnt					smallint NOT NULL,
${logic.hsql-only}	line_1st_expns_dt				date,
${logic.hsql-only}	line_last_expns_dt				date,
${logic.hsql-only}	line_place_of_srvc_cd 			varchar(2)  NOT NULL,
${logic.hsql-only}	line_bene_prmry_pyr_cd			char(1),
${logic.hsql-only}	line_icd_dgns_cd 				varchar(7),
${logic.hsql-only}	line_icd_dgns_vrsn_cd			char(1),
${logic.hsql-only}	line_cms_type_srvc_cd			char(1)  NOT NULL,
${logic.hsql-only}	line_hct_hgb_type_cd 			varchar(2),
${logic.hsql-only}	line_hct_hgb_rslt_num			numeric(3,1) NOT NULL,
${logic.hsql-only}	line_ndc_cd 					varchar(11),
${logic.hsql-only}	line_pmt_80_100_cd				char(1),
${logic.hsql-only}	line_prcsg_ind_cd 				varchar(2),
${logic.hsql-only}	line_service_deductible			char(1),
${logic.hsql-only}	prtcptng_ind_cd					char(1),
${logic.hsql-only}	line_sbmtd_chrg_amt				numeric(10,2) NOT NULL,
${logic.hsql-only}	line_alowd_chrg_amt				numeric(10,2) NOT NULL,
${logic.hsql-only}	line_coinsrnc_amt				numeric(10,2) NOT NULL,
${logic.hsql-only}	line_prmry_alowd_chrg_amt		numeric(10,2) NOT NULL,
${logic.hsql-only}	line_bene_ptb_ddctbl_amt		numeric(10,2) NOT NULL,
${logic.hsql-only}	line_bene_prmry_pyr_pd_amt		numeric(10,2) NOT NULL,
${logic.hsql-only}	line_bene_pmt_amt				numeric(10,2) NOT NULL,
${logic.hsql-only}	line_prvdr_pmt_amt				numeric(10,2) NOT NULL,
${logic.hsql-only}	line_nch_pmt_amt				numeric(10,2) NOT NULL,
${logic.hsql-only}	line_dme_prchs_price_amt		numeric(10,2) NOT NULL,
${logic.hsql-only}	betos_cd 						varchar(3),
${logic.hsql-only}	hcpcs_cd 						varchar(5),
${logic.hsql-only}	hcpcs_1st_mdfr_cd 				varchar(5),
${logic.hsql-only}	hcpcs_2nd_mdfr_cd 				varchar(5),
${logic.hsql-only}	hcpcs_3rd_mdfr_cd 				varchar(5),
${logic.hsql-only}	hcpcs_4th_mdfr_cd 				varchar(5),
${logic.hsql-only}	dmerc_line_mtus_cd				char(1),
${logic.hsql-only}	dmerc_line_mtus_cnt 			integer NOT NULL,
${logic.hsql-only}	dmerc_line_prcng_state_cd 		varchar(2),
${logic.hsql-only}	dmerc_line_supplr_type_cd		char(1),
${logic.hsql-only}	dmerc_line_scrn_svgs_amt		numeric(10,2),
${logic.hsql-only}	prvdr_num 						varchar(10),
${logic.hsql-only}	prvdr_npi 						varchar(12),
${logic.hsql-only}	prvdr_spclty 					varchar(3),
${logic.hsql-only}	prvdr_state_cd 					varchar(2)  NOT NULL,
${logic.hsql-only}	tax_num 						varchar(10)  NOT NULL,
${logic.hsql-only} 	constraint public.bfd1485_dme_claim_lines_pkey
${logic.hsql-only} 	primary key (clm_id, line_num) );

${logic.psql-only} SET max_parallel_workers = 24;
${logic.psql-only} SET max_parallel_workers_per_gather = 20;
${logic.psql-only} SET parallel_leader_participation = off;
${logic.psql-only} SET parallel_tuple_cost = 0;
${logic.psql-only} SET parallel_setup_cost = 0;
${logic.psql-only} SET min_parallel_table_scan_size = 0;

${logic.hsql-only} insert into public.bfd1485_dme_claim_lines(
    ${logic.hsql-only} 	clm_id,
    ${logic.hsql-only} 	line_num,
    ${logic.hsql-only} 	line_srvc_cnt,
    ${logic.hsql-only} 	line_1st_expns_dt,
    ${logic.hsql-only} 	line_last_expns_dt,
    ${logic.hsql-only} 	line_place_of_srvc_cd,
    ${logic.hsql-only} 	line_bene_prmry_pyr_cd,
    ${logic.hsql-only} 	line_icd_dgns_cd,
    ${logic.hsql-only} 	line_icd_dgns_vrsn_cd,
    ${logic.hsql-only} 	line_cms_type_srvc_cd,
    ${logic.hsql-only} 	line_hct_hgb_type_cd,
    ${logic.hsql-only} 	line_hct_hgb_rslt_num,
    ${logic.hsql-only} 	line_ndc_cd,
    ${logic.hsql-only} 	line_pmt_80_100_cd,
    ${logic.hsql-only} 	line_prcsg_ind_cd,
    ${logic.hsql-only} 	line_service_deductible,
    ${logic.hsql-only}  prtcptng_ind_cd,
	${logic.hsql-only}  line_sbmtd_chrg_amt,
	${logic.hsql-only}  line_alowd_chrg_amt,
	${logic.hsql-only}  line_coinsrnc_amt,
	${logic.hsql-only}  line_prmry_alowd_chrg_amt,
	${logic.hsql-only}  line_bene_ptb_ddctbl_amt,
	${logic.hsql-only}  line_bene_prmry_pyr_pd_amt,
	${logic.hsql-only}  line_bene_pmt_amt,
	${logic.hsql-only}  line_prvdr_pmt_amt,
	${logic.hsql-only}  line_nch_pmt_amt,
	${logic.hsql-only}  line_dme_prchs_price_amt,
    ${logic.hsql-only} 	betos_cd,
    ${logic.hsql-only} 	hcpcs_cd,
    ${logic.hsql-only} 	hcpcs_1st_mdfr_cd,
    ${logic.hsql-only} 	hcpcs_2nd_mdfr_cd,
    ${logic.hsql-only} 	hcpcs_3rd_mdfr_cd,
    ${logic.hsql-only} 	hcpcs_4th_mdfr_cd,
    ${logic.hsql-only} 	dmerc_line_mtus_cd,
    ${logic.hsql-only} 	dmerc_line_mtus_cnt,
    ${logic.hsql-only} 	dmerc_line_prcng_state_cd,
    ${logic.hsql-only} 	dmerc_line_supplr_type_cd,
    ${logic.hsql-only} 	dmerc_line_scrn_svgs_amt,
    ${logic.hsql-only} 	prvdr_num,
    ${logic.hsql-only} 	prvdr_npi,
    ${logic.hsql-only} 	prvdr_spclty,
    ${logic.hsql-only} 	prvdr_state_cd,
    ${logic.hsql-only} 	tax_num)
${logic.psql-only} create table public.bfd1485_dme_claim_lines as
select
	${logic.psql-only} cast(clm_id as bigint),
	${logic.psql-only} cast(line_num as smallint),
    ${logic.psql-only} cast(line_srvc_cnt as smallint),
	${logic.hsql-only} convert(clm_id, SQL_BIGINT),
    ${logic.hsql-only} convert(line_num, SQL_SMALLINT),
	${logic.hsql-only} convert(line_srvc_cnt, SQL_SMALLINT),
    line_1st_expns_dt,
    line_last_expns_dt,
    line_place_of_srvc_cd,
    line_bene_prmry_pyr_cd,
    line_icd_dgns_cd,
    line_icd_dgns_vrsn_cd,
    line_cms_type_srvc_cd,
    line_hct_hgb_type_cd,
    line_hct_hgb_rslt_num,
    line_ndc_cd,
    line_pmt_80_100_cd,
    line_prcsg_ind_cd,
    line_service_deductible,
    prtcptng_ind_cd,
    ${logic.psql-only} cast(line_sbmtd_chrg_amt as numeric(10,2)),
	${logic.hsql-only} line_sbmtd_chrg_amt,
    ${logic.psql-only} cast(line_alowd_chrg_amt as numeric(10,2)),
	${logic.hsql-only} line_alowd_chrg_amt,
    ${logic.psql-only} cast(line_coinsrnc_amt as numeric(10,2)),
	${logic.hsql-only} line_coinsrnc_amt,
    ${logic.psql-only} cast(line_prmry_alowd_chrg_amt as numeric(10,2)),
	${logic.hsql-only} line_prmry_alowd_chrg_amt,
    ${logic.psql-only} cast(line_bene_ptb_ddctbl_amt as numeric(10,2)),
	${logic.hsql-only} line_bene_ptb_ddctbl_amt,
    ${logic.psql-only} cast(line_bene_prmry_pyr_pd_amt as numeric(10,2)),
	${logic.hsql-only} line_bene_prmry_pyr_pd_amt,
    ${logic.psql-only} cast(line_bene_pmt_amt as numeric(10,2)),
	${logic.hsql-only} line_bene_pmt_amt,
    ${logic.psql-only} cast(line_prvdr_pmt_amt as numeric(10,2)),
	${logic.hsql-only} line_prvdr_pmt_amt,
    ${logic.psql-only} cast(line_nch_pmt_amt as numeric(10,2)),
	${logic.hsql-only} line_nch_pmt_amt,
    ${logic.psql-only} cast(line_dme_prchs_price_amt as numeric(10,2)),
	${logic.hsql-only} line_dme_prchs_price_amt,
    betos_cd,
    hcpcs_cd,
    hcpcs_1st_mdfr_cd,
    hcpcs_2nd_mdfr_cd,
    hcpcs_3rd_mdfr_cd,
    hcpcs_4th_mdfr_cd,
    dmerc_line_mtus_cd,
    dmerc_line_mtus_cnt,
    dmerc_line_prcng_state_cd,
    dmerc_line_supplr_type_cd,
    ${logic.psql-only} cast(dmerc_line_scrn_svgs_amt as numeric(10,2)),
	${logic.hsql-only} dmerc_line_scrn_svgs_amt,
    prvdr_num,
    prvdr_npi,
    prvdr_spclty,
    prvdr_state_cd,
    tax_num
from
	public.dme_claim_lines;

${logic.psql-only} alter table public.bfd1485_dme_claim_lines
${logic.psql-only}	ALTER COLUMN clm_id							SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_num						SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_srvc_cnt					SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_place_of_srvc_cd 			SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_cms_type_srvc_cd			SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_hct_hgb_rslt_num			SET NOT NULL,
${logic.psql-only}	ALTER COLUMN dmerc_line_mtus_cnt 			SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_sbmtd_chrg_amt			SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_alowd_chrg_amt			SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_coinsrnc_amt				SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_prmry_alowd_chrg_amt		SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_bene_ptb_ddctbl_amt		SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_bene_prmry_pyr_pd_amt		SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_bene_pmt_amt				SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_prvdr_pmt_amt				SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_nch_pmt_amt				SET NOT NULL,
${logic.psql-only}	ALTER COLUMN line_dme_prchs_price_amt		SET NOT NULL,
${logic.psql-only}	ALTER COLUMN prvdr_state_cd 				SET NOT NULL,
${logic.psql-only}	ALTER COLUMN tax_num 						SET NOT NULL;

${logic.psql-only} alter table public.bfd1485_dme_claim_lines
${logic.psql-only}     add CONSTRAINT bfd1485_dme_claim_lines_pkey PRIMARY KEY (clm_id, line_num);

ALTER TABLE IF EXISTS public.bfd1485_dme_claim_lines
    ADD CONSTRAINT bfd1485_dme_claim_lines_clm_id_to_dme_claims FOREIGN KEY (clm_id)
    	REFERENCES public.bfd1485_dme_claims (clm_id);