${logic.hsql-only} CREATE TABLE IF NOT EXISTS public.bfd1485_partd_events(
${logic.hsql-only} pde_id						bigint NOT NULL,
${logic.hsql-only} bene_id						bigint NOT NULL,
${logic.hsql-only} clm_grp_id					bigint NOT NULL,
${logic.hsql-only} last_updated					timestamp with time zone,
${logic.hsql-only} final_action					char(1) NOT NULL,
${logic.hsql-only} fill_num						integer NOT NULL,
${logic.hsql-only} pd_dt						date,
${logic.hsql-only} qty_dspnsd_num				numeric(10,3) NOT NULL,
${logic.hsql-only} days_suply_num				smallint NOT NULL,
${logic.hsql-only} prod_srvc_id					varchar(19) NOT NULL,
${logic.hsql-only} plan_pbp_rec_num				varchar(3) NOT NULL,
${logic.hsql-only} plan_cntrct_rec_id			varchar(5) NOT NULL,
${logic.hsql-only} prscrbr_id					varchar(15) NOT NULL,
${logic.hsql-only} prscrbr_id_qlfyr_cd			varchar(2) NOT NULL,
${logic.hsql-only} srvc_dt						date NOT NULL,
${logic.hsql-only} srvc_prvdr_id				varchar(15) NOT NULL,
${logic.hsql-only} srvc_prvdr_id_qlfyr_cd		varchar(2) NOT NULL,
${logic.hsql-only} tot_rx_cst_amt				numeric(8,2) NOT NULL,
${logic.hsql-only} cvrd_d_plan_pd_amt			numeric(8,2) NOT NULL,
${logic.hsql-only} ncvrd_plan_pd_amt			numeric(8,2) NOT NULL,
${logic.hsql-only} ptnt_pay_amt					numeric(8,2) NOT NULL,
${logic.hsql-only} rptd_gap_dscnt_num			numeric(8,2) NOT NULL,
${logic.hsql-only} gdc_abv_oopt_amt				numeric(8,2) NOT NULL,
${logic.hsql-only} gdc_blw_oopt_amt				numeric(8,2) NOT NULL,
${logic.hsql-only} othr_troop_amt				numeric(8,2) NOT NULL,
${logic.hsql-only} plro_amt						numeric(8,2) NOT NULL,
${logic.hsql-only} lics_amt						numeric(8,2) NOT NULL,
${logic.hsql-only} adjstmt_dltn_cd				char(1),
${logic.hsql-only} brnd_gnrc_cd					char(1),
${logic.hsql-only} ctstrphc_cvrg_cd				char(1),
${logic.hsql-only} daw_prod_slctn_cd			char(1) NOT NULL,
${logic.hsql-only} dspnsng_stus_cd				char(1),
${logic.hsql-only} drug_cvrg_stus_cd			char(1) NOT NULL,
${logic.hsql-only} nstd_frmt_cd					char(1),
${logic.hsql-only} ptnt_rsdnc_cd				varchar(2) NOT NULL,
${logic.hsql-only} phrmcy_srvc_type_cd			varchar(2) NOT NULL,
${logic.hsql-only} prcng_excptn_cd				char(1),
${logic.hsql-only} submsn_clr_cd				varchar(2),
${logic.hsql-only} cmpnd_cd						integer NOT NULL,
${logic.hsql-only} rx_orgn_cd					char(1),
${logic.hsql-only} rx_srvc_rfrnc_num			bigint NOT NULL,
${logic.hsql-only} CONSTRAINT bfd1485_partd_events_pkey PRIMARY KEY (pde_id));

${logic.psql-only} SET max_parallel_workers = 24;
${logic.psql-only} SET max_parallel_workers_per_gather = 20;
${logic.psql-only} SET parallel_leader_participation = off;
${logic.psql-only} SET parallel_tuple_cost = 0;
${logic.psql-only} SET parallel_setup_cost = 0;
${logic.psql-only} SET min_parallel_table_scan_size = 0;

${logic.hsql-only} insert into public.bfd1485_partd_events(
${logic.hsql-only}		pde_id,
${logic.hsql-only}		bene_id,
${logic.hsql-only}		clm_grp_id,
${logic.hsql-only}		last_updated,
${logic.hsql-only}		final_action,
${logic.hsql-only}		fill_num,
${logic.hsql-only}		pd_dt,
${logic.hsql-only}		qty_dspnsd_num,
${logic.hsql-only}		days_suply_num,
${logic.hsql-only}		prod_srvc_id,
${logic.hsql-only}		plan_pbp_rec_num,
${logic.hsql-only}		plan_cntrct_rec_id,
${logic.hsql-only}		prscrbr_id,
${logic.hsql-only}		prscrbr_id_qlfyr_cd,
${logic.hsql-only}		srvc_dt,
${logic.hsql-only}		srvc_prvdr_id,
${logic.hsql-only}		srvc_prvdr_id_qlfyr_cd,
${logic.hsql-only}		tot_rx_cst_amt,
${logic.hsql-only}		cvrd_d_plan_pd_amt,
${logic.hsql-only}		ncvrd_plan_pd_amt,
${logic.hsql-only}		ptnt_pay_amt,
${logic.hsql-only}		rptd_gap_dscnt_num,
${logic.hsql-only}		gdc_abv_oopt_amt,
${logic.hsql-only}		gdc_blw_oopt_amt,
${logic.hsql-only}		othr_troop_amt,
${logic.hsql-only}		plro_amt,
${logic.hsql-only}		lics_amt,
${logic.hsql-only}		adjstmt_dltn_cd,
${logic.hsql-only}		brnd_gnrc_cd,
${logic.hsql-only}		ctstrphc_cvrg_cd,
${logic.hsql-only}		daw_prod_slctn_cd,
${logic.hsql-only}		dspnsng_stus_cd,
${logic.hsql-only}		drug_cvrg_stus_cd,
${logic.hsql-only}		nstd_frmt_cd,
${logic.hsql-only}		ptnt_rsdnc_cd,
${logic.hsql-only}		phrmcy_srvc_type_cd,
${logic.hsql-only}		prcng_excptn_cd,
${logic.hsql-only}		submsn_clr_cd,
${logic.hsql-only}		cmpnd_cd,
${logic.hsql-only}		rx_orgn_cd,
${logic.hsql-only}		rx_srvc_rfrnc_num)
--
${logic.psql-only} create table public.bfd1485_partd_events as
select
	${logic.psql-only} cast(pde_id as bigint),  
    ${logic.hsql-only} convert(pde_id, SQL_BIGINT),
    ${logic.psql-only} cast(bene_id as bigint),  
    ${logic.hsql-only} convert(bene_id, SQL_BIGINT),
    ${logic.psql-only} cast(clm_grp_id as bigint),  
    ${logic.hsql-only} convert(clm_grp_id, SQL_BIGINT),
    last_updated,
    final_action,
    ${logic.psql-only} cast(fill_num as integer),  
    ${logic.hsql-only} fill_num,
    pd_dt,
    qty_dspnsd_num,
    ${logic.psql-only} cast(days_suply_num as smallint),  
    ${logic.hsql-only} convert(days_suply_num, SQL_SMALLINT),
    prod_srvc_id,
    plan_pbp_rec_num,
    plan_cntrct_rec_id,
    prscrbr_id,
    prscrbr_id_qlfyr_cd,
    srvc_dt,
    srvc_prvdr_id,
    srvc_prvdr_id_qlfyr_cd,
    tot_rx_cst_amt,
    cvrd_d_plan_pd_amt,
    ncvrd_plan_pd_amt,
    ptnt_pay_amt,
    rptd_gap_dscnt_num,
    gdc_abv_oopt_amt,
    gdc_blw_oopt_amt,
    othr_troop_amt,
    plro_amt,
    lics_amt,
    adjstmt_dltn_cd,
    brnd_gnrc_cd,
    ctstrphc_cvrg_cd,
    daw_prod_slctn_cd,
    dspnsng_stus_cd,
    drug_cvrg_stus_cd,
    nstd_frmt_cd,
    ptnt_rsdnc_cd,
    phrmcy_srvc_type_cd,
    prcng_excptn_cd,
    submsn_clr_cd,
    cmpnd_cd,
    rx_orgn_cd,
    ${logic.psql-only} cast(rx_srvc_rfrnc_num as bigint)
    ${logic.hsql-only} convert(rx_srvc_rfrnc_num, SQL_BIGINT)
from
	public.partd_events;

${logic.psql-only} alter table public.bfd1485_partd_events
	${logic.psql-only} alter column pde_id SET NOT NULL,
	${logic.psql-only} alter column bene_id SET NOT NULL,
	${logic.psql-only} alter column clm_grp_id SET NOT NULL,
	${logic.psql-only} alter column cmpnd_cd SET NOT NULL,
	${logic.psql-only} alter column days_suply_num SET NOT NULL,
	${logic.psql-only} alter column daw_prod_slctn_cd SET NOT NULL,
	${logic.psql-only} alter column drug_cvrg_stus_cd  SET NOT NULL,
	${logic.psql-only} alter column fill_num SET NOT NULL,
	${logic.psql-only} alter column rptd_gap_dscnt_num SET NOT NULL,
	${logic.psql-only} alter column gdc_abv_oopt_amt SET NOT NULL,
	${logic.psql-only} alter column gdc_blw_oopt_amt SET NOT NULL,
	${logic.psql-only} alter column lics_amt SET NOT NULL,
	${logic.psql-only} alter column prod_srvc_id SET NOT NULL,
	${logic.psql-only} alter column othr_troop_amt SET NOT NULL,
	${logic.psql-only} alter column cvrd_d_plan_pd_amt SET NOT NULL,
	${logic.psql-only} alter column ncvrd_plan_pd_amt SET NOT NULL,
	${logic.psql-only} alter column plro_amt SET NOT NULL,
	${logic.psql-only} alter column ptnt_pay_amt SET NOT NULL,
	${logic.psql-only} alter column ptnt_rsdnc_cd SET NOT NULL,
	${logic.psql-only} alter column phrmcy_srvc_type_cd SET NOT NULL,
	${logic.psql-only} alter column plan_pbp_rec_num SET NOT NULL,
	${logic.psql-only} alter column plan_cntrct_rec_id SET NOT NULL,
	${logic.psql-only} alter column prscrbr_id SET NOT NULL,
	${logic.psql-only} alter column prscrbr_id_qlfyr_cd SET NOT NULL,
	${logic.psql-only} alter column srvc_dt SET NOT NULL,
	${logic.psql-only} alter column rx_srvc_rfrnc_num SET NOT NULL,
	${logic.psql-only} alter column qty_dspnsd_num SET NOT NULL,
	${logic.psql-only} alter column srvc_prvdr_id SET NOT NULL,
	${logic.psql-only} alter column srvc_prvdr_id_qlfyr_cd SET NOT NULL,
	${logic.psql-only} alter column tot_rx_cst_amt SET NOT NULL,
	${logic.psql-only} alter column final_action SET NOT NULL;

${logic.psql-only} alter table public.bfd1485_partd_events
${logic.psql-only}     add CONSTRAINT bfd1485_partd_events_pkey PRIMARY KEY (pde_id);

CREATE INDEX IF NOT EXISTS bfd1485_partd_events_bene_id_idx
	ON public.bfd1485_partd_events (bene_id);