${logic.hsql-only} CREATE TABLE IF NOT EXISTS public.bfd1485_dme_claims (
${logic.hsql-only}	clm_id							bigint NOT NULL,
${logic.hsql-only}	bene_id							bigint NOT NULL,  
${logic.hsql-only}	clm_grp_id						bigint NOT NULL,
${logic.hsql-only}	last_updated					timestamp with time zone,
${logic.hsql-only}	clm_from_dt						date NOT NULL,
${logic.hsql-only}	clm_thru_dt						date NOT NULL,
${logic.hsql-only}	clm_disp_cd						varchar(2) NOT NULL,
${logic.hsql-only}	clm_clncl_tril_num				varchar(8),
${logic.hsql-only}	clm_pmt_amt						numeric(10,2) NOT NULL,
${logic.hsql-only}	final_action					char(1) NOT NULL,
${logic.hsql-only}	carr_num						varchar(5) NOT NULL,
${logic.hsql-only}	carr_clm_cntl_num				varchar(23), 
${logic.hsql-only}	carr_clm_entry_cd				char(1) NOT NULL, 
${logic.hsql-only}	carr_clm_hcpcs_yr_cd			char(1),
${logic.hsql-only}	carr_clm_cash_ddctbl_apld_amt	numeric(10,2) NOT NULL, 
${logic.hsql-only}	carr_clm_pmt_dnl_cd				varchar(2) NOT NULL,
${logic.hsql-only}	carr_clm_prmry_pyr_pd_amt		numeric(10,2) NOT NULL,
${logic.hsql-only}	carr_clm_prvdr_asgnmt_ind_sw	char(1) NOT NULL, 
${logic.hsql-only}	nch_clm_type_cd					varchar(2) NOT NULL,
${logic.hsql-only}	nch_wkly_proc_dt				date NOT NULL,
${logic.hsql-only}	nch_near_line_rec_ident_cd		char(1) NOT NULL,
${logic.hsql-only}	nch_carr_clm_alowd_amt			numeric(10,2) NOT NULL,
${logic.hsql-only}	nch_clm_bene_pmt_amt			numeric(10,2) NOT NULL,
${logic.hsql-only}	nch_clm_prvdr_pmt_amt			numeric(10,2) NOT NULL,
${logic.hsql-only}	nch_carr_clm_sbmtd_chrg_amt		numeric(10,2) NOT NULL,
${logic.hsql-only}	prncpal_dgns_cd					varchar(7),
${logic.hsql-only}	prncpal_dgns_vrsn_cd			char(1),
${logic.hsql-only}	rfr_physn_npi					varchar(12),
${logic.hsql-only}	rfr_physn_upin					varchar(12),
${logic.hsql-only}	icd_dgns_cd1					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd1				char(1),
${logic.hsql-only}	icd_dgns_cd2					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd2				char(1),
${logic.hsql-only}	icd_dgns_cd3					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd3				char(1),
${logic.hsql-only}	icd_dgns_cd4					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd4				char(1),
${logic.hsql-only}	icd_dgns_cd5					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd5				char(1),
${logic.hsql-only}	icd_dgns_cd6					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd6				char(1),
${logic.hsql-only}	icd_dgns_cd7					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd7				char(1),
${logic.hsql-only}	icd_dgns_cd8					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd8				char(1),
${logic.hsql-only}	icd_dgns_cd9					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd9				char(1),
${logic.hsql-only}	icd_dgns_cd10					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd10				char(1),
${logic.hsql-only}	icd_dgns_cd11					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd11				char(1),
${logic.hsql-only}	icd_dgns_cd12					varchar(7),
${logic.hsql-only}	icd_dgns_vrsn_cd12				char(1),
${logic.hsql-only} 	constraint public.bfd1485_dme_claims_pkey
${logic.hsql-only} 	primary key (clm_id) );

${logic.psql-only} SET max_parallel_workers = 24;
${logic.psql-only} SET max_parallel_workers_per_gather = 20;
${logic.psql-only} SET parallel_leader_participation = off;
${logic.psql-only} SET parallel_tuple_cost = 0;
${logic.psql-only} SET parallel_setup_cost = 0;
${logic.psql-only} SET min_parallel_table_scan_size = 0;

${logic.hsql-only} insert into public.bfd1485_dme_claims(
${logic.hsql-only}	clm_id,
${logic.hsql-only}	bene_id,
${logic.hsql-only}	clm_grp_id,
${logic.hsql-only}	last_updated,
${logic.hsql-only}	clm_from_dt,
${logic.hsql-only}	clm_thru_dt,
${logic.hsql-only}	clm_disp_cd,
${logic.hsql-only}	clm_clncl_tril_num,
${logic.hsql-only}	clm_pmt_amt,
${logic.hsql-only}	final_action,
${logic.hsql-only}	carr_num,
${logic.hsql-only}	carr_clm_cntl_num,
${logic.hsql-only}	carr_clm_entry_cd,
${logic.hsql-only}	carr_clm_hcpcs_yr_cd,
${logic.hsql-only}	carr_clm_cash_ddctbl_apld_amt,
${logic.hsql-only}	carr_clm_pmt_dnl_cd,
${logic.hsql-only}	carr_clm_prmry_pyr_pd_amt,
${logic.hsql-only}	carr_clm_prvdr_asgnmt_ind_sw,
${logic.hsql-only}	nch_clm_type_cd,
${logic.hsql-only}	nch_wkly_proc_dt,
${logic.hsql-only}	nch_near_line_rec_ident_cd,
${logic.hsql-only}	nch_carr_clm_alowd_amt,
${logic.hsql-only}	nch_clm_bene_pmt_amt,
${logic.hsql-only}	nch_clm_prvdr_pmt_amt,
${logic.hsql-only}	nch_carr_clm_sbmtd_chrg_amt,
${logic.hsql-only}	prncpal_dgns_cd,
${logic.hsql-only}	prncpal_dgns_vrsn_cd,
${logic.hsql-only}	rfr_physn_npi,
${logic.hsql-only}	rfr_physn_upin,
${logic.hsql-only}	icd_dgns_cd1,
${logic.hsql-only}	icd_dgns_vrsn_cd1,
${logic.hsql-only}	icd_dgns_cd2,
${logic.hsql-only}	icd_dgns_vrsn_cd2,
${logic.hsql-only}	icd_dgns_cd3,
${logic.hsql-only}	icd_dgns_vrsn_cd3,
${logic.hsql-only}	icd_dgns_cd4,
${logic.hsql-only}	icd_dgns_vrsn_cd4,
${logic.hsql-only}	icd_dgns_cd5,
${logic.hsql-only}	icd_dgns_vrsn_cd5,
${logic.hsql-only}	icd_dgns_cd6,
${logic.hsql-only}	icd_dgns_vrsn_cd6,
${logic.hsql-only}	icd_dgns_cd7,
${logic.hsql-only}	icd_dgns_vrsn_cd7,
${logic.hsql-only}	icd_dgns_cd8,
${logic.hsql-only}	icd_dgns_vrsn_cd8,
${logic.hsql-only}	icd_dgns_cd9,
${logic.hsql-only}	icd_dgns_vrsn_cd9,
${logic.hsql-only}	icd_dgns_cd10,
${logic.hsql-only}	icd_dgns_vrsn_cd10,
${logic.hsql-only}	icd_dgns_cd11,
${logic.hsql-only}	icd_dgns_vrsn_cd11,
${logic.hsql-only}	icd_dgns_cd12,
${logic.hsql-only}	icd_dgns_vrsn_cd12 )
${logic.psql-only} create table public.bfd1485_dme_claims as
select
	${logic.psql-only} cast(clm_id as bigint),
	${logic.psql-only} cast(bene_id as bigint),
	${logic.psql-only} cast(clm_grp_id as bigint),  
    ${logic.hsql-only} convert(clm_id, SQL_BIGINT),
	${logic.hsql-only} convert(bene_id, SQL_BIGINT),
	${logic.hsql-only} convert(clm_grp_id, SQL_BIGINT),
	last_updated,
	clm_from_dt,
    clm_thru_dt,
    clm_disp_cd,
    clm_clncl_tril_num,
    clm_pmt_amt,
    final_action,
    carr_num,
    carr_clm_cntl_num,
    carr_clm_entry_cd,
    carr_clm_hcpcs_yr_cd,
    carr_clm_cash_ddctbl_apld_amt,
    carr_clm_pmt_dnl_cd,
    carr_clm_prmry_pyr_pd_amt,
    carr_clm_prvdr_asgnmt_ind_sw,
    nch_clm_type_cd,
    nch_wkly_proc_dt,
    nch_near_line_rec_ident_cd,
    nch_carr_clm_alowd_amt,
    nch_clm_bene_pmt_amt,
    nch_clm_prvdr_pmt_amt,
    nch_carr_clm_sbmtd_chrg_amt,
    prncpal_dgns_cd,
    prncpal_dgns_vrsn_cd,
    rfr_physn_npi,
    rfr_physn_upin,
    icd_dgns_cd1,
    icd_dgns_vrsn_cd1,
    icd_dgns_cd2,
    icd_dgns_vrsn_cd2,
    icd_dgns_cd3,
    icd_dgns_vrsn_cd3,
    icd_dgns_cd4,
    icd_dgns_vrsn_cd4,
    icd_dgns_cd5,
    icd_dgns_vrsn_cd5,
    icd_dgns_cd6,
    icd_dgns_vrsn_cd6,
    icd_dgns_cd7,
    icd_dgns_vrsn_cd7,
    icd_dgns_cd8,
    icd_dgns_vrsn_cd8,
    icd_dgns_cd9,
    icd_dgns_vrsn_cd9,
    icd_dgns_cd10,
    icd_dgns_vrsn_cd10,
    icd_dgns_cd11,
    icd_dgns_vrsn_cd11,
    icd_dgns_cd12,
    icd_dgns_vrsn_cd12
from
	public.dme_claims;

${logic.psql-only} alter table public.bfd1485_dme_claims
${logic.psql-only}     alter column clm_id SET NOT NULL,
${logic.psql-only}     alter column bene_id SET NOT NULL,  
${logic.psql-only}     alter column clm_grp_id SET NOT NULL,
${logic.psql-only}     alter column clm_from_dt SET NOT NULL,
${logic.psql-only}     alter column clm_thru_dt SET NOT NULL,
${logic.psql-only}     alter column clm_disp_cd SET NOT NULL,
${logic.psql-only}     alter column clm_pmt_amt SET NOT NULL,
${logic.psql-only}     alter column final_action SET NOT NULL,
${logic.psql-only}     alter column carr_num SET NOT NULL,
${logic.psql-only}     alter column carr_clm_entry_cd SET NOT NULL, 
${logic.psql-only}     alter column carr_clm_cash_ddctbl_apld_amt SET NOT NULL, 
${logic.psql-only}     alter column carr_clm_pmt_dnl_cd SET NOT NULL,
${logic.psql-only}     alter column carr_clm_prmry_pyr_pd_amt SET NOT NULL,
${logic.psql-only}     alter column carr_clm_prvdr_asgnmt_ind_sw SET NOT NULL, 
${logic.psql-only}     alter column nch_clm_type_cd SET NOT NULL,
${logic.psql-only}     alter column nch_wkly_proc_dt SET NOT NULL,
${logic.psql-only}     alter column nch_near_line_rec_ident_cd SET NOT NULL,
${logic.psql-only}     alter column nch_carr_clm_alowd_amt SET NOT NULL,
${logic.psql-only}     alter column nch_clm_bene_pmt_amt SET NOT NULL,
${logic.psql-only}     alter column nch_clm_prvdr_pmt_amt SET NOT NULL,
${logic.psql-only}     alter column nch_carr_clm_sbmtd_chrg_amt SET NOT NULL;

${logic.psql-only} alter table public.bfd1485_dme_claims
${logic.psql-only}     add CONSTRAINT bfd1485_dme_claims_pkey PRIMARY KEY (clm_id);

CREATE INDEX IF NOT EXISTS bfd1485_dme_claims_bene_id_idx
	ON public.bfd1485_dme_claims (bene_id);